### ISSUE TITLE
Unable to upload keepass xml neither csv files

### ISSUE THREAD

**Issue by Mad-Dax** [nilsteampassnet/TeamPass#1013]
Hi Nils,

i have a problem with importing an existing keepass database. from ubuntu to our vpn server, where teampass is running in a docker.

I installed teampass 2.1.23 successfully and came to the last step with importing a keepass database.
I am using ubuntu and keepassx and i already found out, that teampass is unable to handle kdbx. So i exported my kdbx to an older version (keepass 1.x) on my windows and exported it again as .xml and it's still showing me "can’t read file, must be a keepass file".
When i try to upload a .csv it doesn't let me even upload, because i can't choose a path to upload the file to
![bildschirmfoto vom 2015-07-14 10 16 27](https://cloud.githubusercontent.com/assets/10218382/8669050/6c1c92ae-2a11-11e5-9c60-4b11d49d76f9.png)

i enabled the error_log in the php.ini but its not showing anything except 1 line in apache2
[Tue Jul 14 08:13:49.052773 2015] [:error] [pid 1543] [client 10.150.0.6:34285] PHP Notice:  Undefined variable: prevLevel in /opt/TeamPass-2.1.23/items.import.php on line 113, referer: http://x.x.x.x:8008/teampass/index.php?page=items

What can i do to make it work? its the only thing i stuck on. And btw. did you remove the homebutton? i am missing this also in the panel.
![bildschirmfoto vom 2015-07-14 10 21 24](https://cloud.githubusercontent.com/assets/10218382/8669123/19d1b80c-2a12-11e5-85cf-320509163d22.png)

**Comment by jkubler** [comment]
Hi, i have the same problem. Did you resolved it?

**Comment by drsadmin** [comment]
The teampass dev has logged a ticket with the csrf folks, with no resolution so far, URL is here:

https://github.com/mebjas/CSRF-Protector-PHP/issues/40

My investigation revealed that the file to be imported never makes it into folder teampass/files. The best workaround is to transfer the file to that directory manually yourself using the exact same filename. Make sure it is owned by the apache user which in my case is www-data. I made it read only just in case but that might not be necessary. Then go through the import process again and it will work.

The other workaround given for this problem which disables csrf breaks the teampass login for me so this is the best work around I found.

**Comment by mebjas** [comment]
@drsadmin @Mad-Dax 
I wasn't able to reproduce the bug notified in the issue. I was able to upload files with CSRF Protection enabled, both in `Chrome` & `Firefox`.

I'd test it for `teampass`, could you point me to some straight forward way to reproduce this bug.

**Comment by drsadmin** [comment]
It's not easy to reproduce as we don't know if the problem is server side or client side first of all. Client side there are too many combinations of browsers, browser versions, and important browser settings. Server side I'm just using the download of Teampass 2.1.25 with apache on Ubuntu 14.04 supplied php version etc.

The code responsible for uploading the file is plupload which complicates diagnosis as it uses too many options for handling the upload. If we can get a temporary simpler HTML5 interface to perform the POST operation / upload then we could probably make some progress on trying to debug the use of plupload if necessary.

The CSRF bug ticket says that plupload never gets the parameters it needs from the browser which is running the java script for plupload? All plupload fallbacks, like Flash, Silverlight and Java (still in development) seem to be enabled by teampass but not yet HTML5. That seems a bit out of date now. Quote from the CSRF ticket:

"it seems that all "POST" parameters that should be send with plupload are not sent when CSRF protector is enabled"
