### ISSUE TITLE
Encription Keys Question

### ISSUE THREAD

**Issue by locke520** [nilsteampassnet/TeamPass#1038]
I've installed the latest version and got everything working fine.

However after poking around in the database I'm a bit confused about the existence of keys table. How do these keys relate to the encrypted password? I know that they are not simply the key in plain text ( as I've tested it).

Would anyone be able to explain how this works or point me at the relevant bits of code?

**Comment by nilsteampassnet** [comment]
Since 2.1.23, Teampass relies on [PHPCrypt](http://www.gilfether.com/phpcrypt/) library to encrypt/decrypt the credentials inside the database.

The cipher used in AES-128 encryption with CBC mode. This level is the standard recommended because it has a very good balance between security and required resources.
