### ISSUE TITLE
No more docs ...

### ISSUE THREAD

**Issue by zephilou** [nilsteampassnet/TeamPass#1050]
As the website is down and the github's wiki is empty, is there a release date for an available (and up to date) docs section.

Thks

**Comment by vkreker** [comment]
This domain name expired on Oct 30 2015 12:30:52:000PM  :(

**Comment by tholken** [comment]
But its only September so that's not it.  DNS seems to send to a parked domain.

http://network-tools.com/default.asp?prog=express&host=teampass.net

WHOIS
<SNIP>
 Domain Name: TEAMPASS.NET
   Registrar: PDR LTD. D/B/A PUBLICDOMAINREGISTRY.COM
   Sponsoring Registrar IANA ID: 303
   Whois Server: whois.PublicDomainRegistry.com
   Referral URL: http://www.PublicDomainRegistry.com
   Name Server: NS1.HALFDOLLARHOSTING.US
   Name Server: NS2.HALFDOLLARHOSTING.US
   Status: clientTransferProhibited http://www.icann.org/epp#clientTransferProhibited
   Updated Date: 28-oct-2014
   Creation Date: 30-oct-2011
   Expiration Date: 30-oct-2015

>>> Last update of whois database: Thu, 01 Oct 2015 03:24:02 GMT <<<

**Comment by ktb92677** [comment]
Is there an ETA on when the site will be back online?

**Comment by nilsteampassnet** [comment]
Should be back since this afternoon. 
If not, please clear your browser cache. 

All my apologies, I forgot to pay the bill for the domain name.
