### ISSUE TITLE
Missing Features \ Components

### ISSUE THREAD

**Issue by jmac886** [nilsteampassnet/TeamPass#1072]
Just installed Teampass 2.1.23 on Server 2008 R2. Install was successful. However, it looks like some components are missing such as "Folder tree","Add\delete Items". 
![teampass_screenshot](https://cloud.githubusercontent.com/assets/15602990/10872715/9e5e3c7a-80bc-11e5-958c-c675b389a044.JPG)

**Comment by nilsteampassnet** [comment]
​Administrator accounts cannot access by default to Items.​
You need to create other users (managers, normal or read-only) to access
and manage Items.
This is for security reasons because administrator account cannot be
"restricted".

If you want you can by pass this security feature by following information
given in this [page](
http://teampass.net/2014-04-19-change-administrator-usage/).

**Comment by jmac886** [comment]
Thank You – It worked.

Can you please help me on another issue – I get “forbidden” error message from Apache when accessed via browser.

[cid:image001.png@01D11587.81C20740]


Regards,

Jason

**Comment by nilsteampassnet** [comment]
I don't really understand the point.

Can you send a screen-capture?
