### ISSUE TITLE
Menu unavailable

### ISSUE THREAD

**Issue by mibalas** [nilsteampassnet/TeamPass#1091]
I installed TP v2.1.23 and when I logged in with admin user I noticed that the side menu doesnt appear and the top menu had less itens then usually.

This way I can't add passwords :(

Whats the problem with my installation?

I tried in chrome, ff and ie.

i'm using apache 2.4 and php 5.5.9

![tp_error](https://cloud.githubusercontent.com/assets/15907968/11242640/1e459660-8dea-11e5-9340-33391bd5c1c2.png)

**Comment by nilsteampassnet** [comment]
Please use 2.1.24 version which is the last release.

Concerning what you saw, please refer to this[PAGE](http://teampass.net/2014-04-19-change-administrator-usage/)

**Comment by mibalas** [comment]
Hi, thanks for reply.

I did what you recommended and now its working properly, thanks!

but...

now I have another problem, I can't associate a user with a role, when I create a user and add the role in user management, it does not save.

So I cant add passwords because its showing a message: " You are not allowed to see that Item!"

![tp_error2](https://cloud.githubusercontent.com/assets/15907968/11276569/ba124144-8ec9-11e5-8e77-cdaa90c71853.png)

**Comment by nilsteampassnet** [comment]
Teampass has not be build for having Administrator as users.
So sure a work-around exists but it is not a recommended way to use TP currently.
I need to make it more robust for such usage.

You should change User1 to not admin in a 1st step.

**Comment by nilsteampassnet** [comment]
​This case is quite complex.
By default, Teampass is not designed to permit Admin to access Items.
A workaround was found in order to permit some user to do it.
But all tweaks concerning the access on folders don't work in this case.
Indeed my point of view is that if a Teampass instance is using the
workaround, then it means that the Admin has access to everything in the
database.
​Now if an Admin needs some more refined access rights, then he should not
be defined as "admin" but as "Manager" or normal user.

**Comment by mibalas** [comment]
I understand that point.

I create a manager user to add passwords, its working normally now.

TP its a amazing system.

thanks for all support
