### ISSUE TITLE
"Cannot redeclare class Encryption\Crypt\aesctr"

### ISSUE THREAD

**Issue by H4Mm3r** [nilsteampassnet/TeamPass#1105]
Hello,

Since my PHP 5.6 upgrade, I've got this error ont the login POST : 

array(4) {
  ["type"]=>
  int(64)
  ["message"]=>
  string(46) "Cannot redeclare class Encryption\Crypt\aesctr"
  ["file"]=>
  string(64) "/var/www/teampass/includes/libraries/Encryption/Crypt/aesctr.php"
  ["line"]=>
  int(11)
}

Teampass Release : 2.1.19

Thakns by advance

**Comment by nilsteampassnet** [comment]
​What are the steps to repr​oduce this?
What version?

**Comment by H4Mm3r** [comment]
Hi,

Teampass Release : 2.1.19, php 5.6

When connecting I have a 500 on the POST, I have var_dumped the error above...

Thanks

**Comment by H4Mm3r** [comment]
Hello,

I even can't make a fresh install, I've got a 500 on the "Install" POST.

Apache 2.6, PHP 5.6

**Comment by mbartele** [comment]
Have you found any solution?
I am having this issue installing teampass on Ubuntu 14.04.4 and PHP 5.5.9
Other users are also having this problem #1204 and #1218

**Comment by mbartele** [comment]
Hello,

I was facing the same problem today and was able to resolve the issue. I ran into some forum posts stating that in certain versions of PHP, the parent class have to be declared before the extended class.

I edited the "includes\libraries\Encryption\Crypt\aesctr.php" class so that the Aes class is declared before the aesctr class (by just cutting the Aes class part under the aesctr class and pasting it before it).

Unfortunately I have absolutely no PHP experience so I am not able to give a further explanation for this if that is necessary.

I hope I helped some of you out.

Mark

**Comment by H4Mm3r** [comment]
Hi,

Still not working after this change :(

**Comment by mbartele** [comment]
Are you using LDAP?

**Comment by ymakhloufi** [comment]
@mbartele: That worked like a charm!

**Comment by javimoyabrava** [comment]
> Hello,
> 
> I was facing the same problem today and was able to resolve the issue. I ran into some forum posts stating that in certain versions of PHP, the parent class have to be declared before the extended class.
> 
> I edited the "includes\libraries\Encryption\Crypt\aesctr.php" class so that the Aes class is declared before the aesctr class (by just cutting the Aes class part under the aesctr class and pasting it before it).
> 
> Unfortunately I have absolutely no PHP experience so I am not able to give a further explanation for this if that is necessary.
> 
> I hope I helped some of you out.
> 
> Mark

Estimate
best regard
Being a beginner user, can you send me the correct step by step to apply this solution, since I am trying to update to the version  [TeamPass 2.1.27] to [TeamPass 3.0.0.18]


![image](https://user-images.githubusercontent.com/106878817/179599769-81e74210-4687-4ae2-afbf-a1f4ab3eb1fb.png)
![image](https://user-images.githubusercontent.com/106878817/179599861-48d4ae5c-784d-4c90-9018-0166b6dd43a8.png)
