### ISSUE TITLE
Not connect.n Verify Network

### ISSUE THREAD

**Issue by jamesBru** [nilsteampassnet/TeamPass#1120]
As user when I click on multiple file following , I get this error : Not connect.n Verify Network

**Comment by frankenstein91** [comment]
same problem on my system. 
if i switch from one user folder to a group folder

**Comment by nilsteampassnet** [comment]
​I did not understood how to reproduce this.
Can you give me the steps?

Thanks

**Comment by frankenstein91** [comment]
I have new information for you to reproduce the problem. 
The problem is not caused by the allocated rights or the folder itself.

It caused by to fast switching from one folder to an other forlder. I never think about it becouse all folders are very small but now we have a big folder.
![2015-12-16 15_41_19-teampass](https://cloud.githubusercontent.com/assets/2527348/11843758/92369b0a-a40b-11e5-8b89-8f5d0b8e9f3d.png)

If the users wait longer, no problem caused.

**Comment by fd4485** [comment]
Hi,
another error when I select an object in a folder I have this error:
![image](https://cloud.githubusercontent.com/assets/11784255/11894890/87c08e04-a57a-11e5-8dfe-85f76d57c765.png)

Thanks

**Comment by fd4485** [comment]
I just correct tree.php and error disappear

https://github.com/nilsteampassnet/TeamPass/issues/1124

**Comment by nilsteampassnet** [comment]
​Please don't mix different topics in the same ticket, it is too difficult
to follow ;)

So topic with message "Not Connect...." is corrected in 2.1.25.
@frankenstein91, thank you for the way to reproduce!
