### ISSUE TITLE
[2.1.24] Mots de passe perdus

### ISSUE THREAD

**Issue by bouba9431** [nilsteampassnet/TeamPass#1127]
Bonjour,

Après la mise à jour depuis la version 2.1.23, tous les mots de passe semblent perdus. Les autres informations des items sont par contre visible.
Est ce qu'il existe une autre alternative à part la ressaisie des mots de passe ? Est ce que le problème est susceptible de se reproduire ?

Merci par avance,

**Comment by nilsteampassnet** [comment]
​Can you please provide me the file install/upgrade.log​ by email?

Since 2.1.24 the encryption protocol has changed which requires a
re-encryption of existing passwords if you upgrade from a previous version.
This seems to be your case.
Based upon my test, the upgrade process should correctly re-encrypt those
passwords, but it relies on the sk.php file.
A log file is generated and it could help to understand what happened
during this process on your server.

Thanks

**Comment by bouba9431** [comment]
Bonjour,

Voici le log. Si tu le souhaites, je complète ma demande initiale en
anglais.

merci d'avance,

2015-12-22 14:19 GMT+01:00 Nils Laumaillé <notifications@github.com>:

**Comment by Zatalyz** [comment]
I have the same problem. My log here : https://khaganat.net/pastebin/view/55fea979

For my update : I had download the new zip in github, and unzip it on my server. I change my old folder in "teampass-bak" and rename the new in "teampass", and copy my file "includes/setting.php" in the new folder. Then I go on teampass/install/upgrade.php and follow instructions. No big problem, but all password has corrupted after update...

I can dump my old database, so it's not a big problem, but my installation is not update for the moment.

**Comment by Zatalyz** [comment]
I try today to migrate again, and it's the same : all password are corrupted. Have you an idea to bypass this problem ? It's not safe to stay in a old version of teampass...

**Comment by nilsteampassnet** [comment]
Do you think I can access your server?

**Comment by Zatalyz** [comment]
I prefer don't open access :D but if you want more logs, I can find it (I see my old log is outdated).

**Comment by nilsteampassnet** [comment]
Using AMMYY is quite safe. No port to open.
Through log it is impossible, too many changes have occurred since 2.1.24.
I would need to perform the upgrade on my own to try to help.

**Comment by Zatalyz** [comment]
Ok, I installed new teampass on my local server, and copy-paste "at hand" my hundred password from my old install. After that, export my work, and import after update on my online server. And it's work. Fortunately I have no more password :) 

This problem is only for old version, so I hope no other people have the same problem now. 

Sorry for long time before answers. And thanks a lot for your useful software, it's the better in free software :+1:

**Comment by nilsteampassnet** [comment]
Thank you for your feedback.
Yes this issue is terrible and I really have investigate during long hours (certainly days) but could not found the way to reproduce entirely. As a consequence I could not propose a correct patch.
Teampass database structure has evolved since and such an encryption change in the future would be more controlled if it happens.
