### ISSUE TITLE
403 Access Forbidden by CSRFProtector! at config save

### ISSUE THREAD

**Issue by gusfersa** [nilsteampassnet/TeamPass#1181]
403 Access Forbidden by CSRFProtector!
Error occurred while trying to save the system settings
Release 2.1.25.0 and 2.1.25.2

http://domain.com/index.php?page=manage_settings
<img width="375" alt="captura de pantalla 2016-02-01 a las 16 19 58" src="https://cloud.githubusercontent.com/assets/3491987/12731936/34146f00-c901-11e5-8488-da302e7820e5.png">

**Comment by paulojjs** [comment]
Hi,

I had the same issue. You should have a csrfp/libs/csrfp.config.php file, check if the jsUrl parameter has the correct value (it needs to be the full url to get the includes/libraries/csrfp/js/csrfprotector.js file).

**Comment by soporteuea** [comment]
I found the error:
`"jsUrl" => "http://domain.com//includes/libraries/csrfp/js/csrfprotector.js"`

The solution:
`"jsUrl" => "http://domain.com/includes/libraries/csrfp/js/csrfprotector.js"`

**Comment by gusfersa** [comment]
Thanks it was the solution

**Comment by pedrocerqueira** [comment]
Hello,

i have the same error and my jsUrl is correct, can you help me

![image](https://cloud.githubusercontent.com/assets/17256105/13055945/1c2ff31e-d40a-11e5-9358-91d590d5021b.png)

**Comment by nilsteampassnet** [comment]
@gusfersa, Indeed I have robustified the creation of this path to jsUrl.

@pedrocerqueira, can you give us the jsurl variable content?

**Comment by dubaid** [comment]
This issues happen because the jsurl are set statically on install process.
If the cpassman_url is changed, the jsurl are not updated and the load of the csrf js file stops working correctly after that.
The file includes/libraries/csrfp/libs/csrfp.config.php must have the line bellow to works, and the install process need to be changed to set value. 

"jsUrl" => $_SESSION['settings']['cpassman_url']."/includes/libraries/csrfp/js/csrfprotector.js",

**Comment by churusaa** [comment]
I'm also getting this same 403 Access Forbidden by CSRFProtector error when trying to save settings.

I have tried your robustified jsUrl in place of the usual jsUrl in the config file, and I still get the same thing. This is a brand new, virgin install of the latest version of TeamPass, and I have confirmed that with the exact URL copied and pasted from my config file, I actually get the text of csrfprotector.js. The distribution I'm running is CentOS 7, but I have made sure to allow write access by the server account

`   "jsPath" => "../js/csrfprotector.js",
#   "jsUrl" => $_SESSION['settings']['cpassman_url']."/includes/libraries/csrfp/js/csrfprotector.js",
# Old jsUrl format:
   "jsUrl" => "https://sub.domain.com/teampass/includes/libraries/csrfp/js/csrfprotector.js",`

I did have to do the following to get even this far, but it's just because this is an Enterprise Linux distro:

`find teampass -type d -exec chmod 755 {} \;
find teampass -type f -exec chmod 644 {} \;

semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/html/teampass/install'
restorecon '/var/www/html/teampass/install'
semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/html/teampass/includes'
restorecon '/var/www/html/teampass/includes'
semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/html/teampass/files'
restorecon '/var/www/html/teampass/files'
semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/html/teampass/upload'
restorecon '/var/www/html/teampass/upload'
semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/html/teampass/includes/avatars'
restorecon '/var/www/html/teampass/includes/avatars'
semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/html/teampass/includes/libraries/csrfp/log'
restorecon '/var/www/html/teampass/includes/libraries/csrfp/log'`

**Comment by nilsteampassnet** [comment]
As you can see above your post, I've committed a fix for this bug among others.
In order to solve until I release a new version, you can take over the file /sources/admin.settings.php on your instance ;)

**Comment by zhanko73** [comment]
Hi Churusaa

I'm not sure if you teampass is finally started to work or not.
I have exactly the same issue, however this was an upgrade from an earlier version.
It is not clear for me what I should "take over" from the admin.settings.php to make it work.

Any idea?

Hank

**Comment by zhanko73** [comment]
Hi Churusaa

It seems in my case I found something. The csrfp.config.php file contains the TOKEN and its lenght.
Due to wrong access I had to manually setup this csrfp.config.php file (generate token etc).
I accidentally left the token lenght on 25, while the token is actually 50 character long.
So I suggest to take a look on the tokenLenght variable in csrfp.config.php file if it matches the lenght of the CSRFP_TOKEN variable.
Good luck. :)

Hank

**Comment by churusaa** [comment]
Thanks zhanko73, I'll have to take a look at that and see if that's what
I've got going on as well (or similar). Good to know CSRFP would rather
give a false positive than a false negative.

**Comment by zhanko73** [comment]
churusaa: Did it help in your problem?

**Comment by churusaa** [comment]
Actually just got it working today. I'm not sure which steps did it (maybe
all three), but I set a new token value, manually updated all of the
references in the DB pointing to my old hostname, and found a few SELinux
policies in CentOS's troubleshooter related to (Unify?) httpd and enabled
an SEBoolean value (the exact name of which escapes me now).

I can happily report that I'm up and running with the .25 release,
especially seeing as how I'm not clever enough to figure out how to check
out branches on GitHub. Seriously, I have a second TeamPass instance that I
cloned, and I couldn't figure out how to change branches. I'm going to have
to ask my wife to teach me Git again. :P

Thanks for following up!
Nathanael
