### ISSUE TITLE
open/highlight folder tree of displayed item

### ISSUE THREAD

**Issue by joebex** [nilsteampassnet/TeamPass#1186]
Hi!
Would it be possible to open the corresponding folder in the folder tree when displaying an item out of the search window? At the moment changes in the item view (right windows) does not affect the tree view on the left which is very confusing when opening items from search results.
Thank you very much!
Jakob
![unbenannt](https://cloud.githubusercontent.com/assets/12139897/12756629/dd642450-c9d4-11e5-8400-779f9d8e0513.png)

**Comment by joebex** [comment]
any ideas?

**Comment by joebex** [comment]
Great, Thank You!

**Comment by Alfred-BE-X** [comment]
Hi! I am a colleague of Jakob and we are now testing version 2.1.26 and while what he describes is indeed fixed in this version by clicking on the entry, there is another problem with the folder tree. Whenever you receive an URL of an entry and consequently browse there, the folder tree does not update, but remains at the old position and clicking on the entry does nothing.

**Comment by nilsteampassnet** [comment]
Finally found a solution for this one.
Committed in 655d3586368eefb32ae95afdf5a706a3b3111402

**Comment by Alfred-BE-X** [comment]
We have a test server set up with the latest version and if the fix is included in 2.1.26.13 it does not work for us. 

Let me explain the problem: Let's say I have 2 parent folders, A and B. Both of these folders have several child folders, lets call them AA, AB, AC and BA, BB, BC respectively. Now suppose I have Teampass opened in the browser and I am looking at an item in folder AB. I then click on a link to an item in folder BC in another browser tab - a new tab opens showing the correct entry in the right pane, but the folder tree on the left still shows me as being in folder AB. What happens basically is that the tree structure is not updated to the item that is shown in the right pane.
