### ISSUE TITLE
Update from 2.1.2 to 2.1.25 not working

### ISSUE THREAD

**Issue by yssvic** [nilsteampassnet/TeamPass#1200]
Hello, 

I try to update a 2.1.2 version to the latest one. Directly upgrading it to the 2.1.25 is not working, it hangs on the screen to check directories. When I upgrade to 2.1.20 I get it running but I can't login because I think it did not correctly used the salt key, the created file sk.php was empty I even entered the salt key that we used in 2.1.2 in the field 'SALT' but not working. 

I tried to find the older versions 2.1.3 etc, so I could do an upgrade version by version but I can't find the older 2.1.3 versions. 

Thank you for this great tool. 

Please help, thank you.

**Comment by OlegSmirnov** [comment]
Hey yssvic/nilsteampassnet,

I recently upgraded from 2.1.9 to 2.1.25 and I found a tricky issue so post it here so you can share.
![teampass1](https://cloud.githubusercontent.com/assets/13546434/13415987/316478c0-dfc4-11e5-92cf-9b62f74e9e8d.PNG)
Here's the initial screen. It actually throws an exception "Undefined variable: abs_path in /var/www/html/install/upgrade.php on line 447," 
It doesn't matter if you fix that manually or replace the path in the filed - this page doesn't work once it failed so basically the whole upgrade is screwed. By 'doesn't work' I mean it doesn't give you any errors or anything neither apache log generates it.
You have to specify full path and only then click 'Launch'.
![teampass2](https://cloud.githubusercontent.com/assets/13546434/13416087/cdff7ad6-dfc4-11e5-909b-9eb514dd9a5f.PNG)

Another couple of thing not mentioned in upgrade documentation:
1) The script won't fix your sk.php file. You have to update SALT by yourself.
2) You have to copy settings.php manually into new /includes directory. Kind of obvious but not mentioned anywhere either.
3) Since some point Teampass requires php-mbstring. Kind of minor but still.

**Comment by yssvic** [comment]
Thank you for your reply, truly appreciated. 

1/ that means you have to enter the salt key yourself in the first field of the sk.php after the update and before running the application? 
2/ is that before running the upgrade? 
3/ thanks

Have a great day, 

Vic

**Comment by OlegSmirnov** [comment]
You got it man.

Thanks

**Comment by yssvic** [comment]
Oleg, It didn't work. 

since I missed a few updates, can you tell me if your sk.php before the update is like this, or did you also filled in the fields AKEY IKEY SKEY AND HOST? mine are empty: 

@define('SALT', 'THISISMYSALINHERE'); //Never Change it once it has been used !!!!!
@define('COST', '13'); // Don't change this.
@define('AKEY', '');
@define('IKEY', '');
@define('SKEY', '');
@define('HOST', '');

THANKS!

**Comment by OlegSmirnov** [comment]
You don't need to create this file manually, the upgrade script handles that.
I just put my salt in once it's done.
If your script doesn't create this file, something went wrong.
I would check apache logs but I can't really help with this, sorry.

**Comment by yssvic** [comment]
Thanks Oleg, just wanted to check it. 

I modified some session variables in the update script and guess what, I succeed in upgrading it :-) 

I will brush up and post a fix. Thanks for your help!

**Comment by OlegSmirnov** [comment]
No worries, glad you made it!
