### ISSUE TITLE
cannot upload any file to TeamPass

### ISSUE THREAD

**Issue by strevithick** [nilsteampassnet/TeamPass#1207]
This appears to be the same problem as #665. I am unable to upload any file, regardless of type to TeamPass. The server environment is completely under my control. Several WP sites also reside on server and uploads work fine with these. 

As I am not able to upload files, I cannot import a KeePass XML file which I need to begin using the software.

I don't mind troubleshooting this, but I need some guidance on where to begin. I'm not seeing any clues in the Apache error logs.

I would like to use this for my IT company.

**Comment by GTSLiDe** [comment]
Try the work around I did in this issue: #1191 

Edit "includes/libraries/csrfp/libs/csrfp.config.php" and change the jsUrl url to something else so that it does not load the file.  When csrfprotector.js is loaded, it will break the upload/import functionality.

Note: this will break the settings page. You wont be able to save the configuration in the settings page unless you revert back jsUrl to the original value.

This is just a temporary work around until someone can find the root cause and fix it in the next version.

**Comment by nilsteampassnet** [comment]
I've struggled a long on this too.

I finally decided to try with Chrome and no problem.
But problem in Firefox.

Can you please tell me if you have tried with CHrome?

**Comment by nilsteampassnet** [comment]
Treated in #1206
