### ISSUE TITLE
Feature Request: User Access Based on AD Group Membership

### ISSUE THREAD

**Issue by hexxamillion** [nilsteampassnet/TeamPass#1217]
I was wondering if there can be a feature to configure role access based on AD group membership. So if a user is added and they are part of a specific AD group then they automatically have access to the shared folders and items based on the role that has that access within Teampass. This could be an option when adding a new role and maybe enabling the feature through admin settings.

**Comment by Idriel** [comment]
That feature would be great. To me that is strange that it does not have this option so we can create Role that is mapped with AD group and then solution read's AD auth user group membership. 

For that we will need to create some "custom" parser that will query AD and then populate Teampass and hack's in DB directly maybe so that solution dont think it's local user . 

Is there any news on this Feature req. Will it be maybe in some feature?
