### ISSUE TITLE
Import from Keepass: missing items with the same title

### ISSUE THREAD

**Issue by podshivalovdv** [nilsteampassnet/TeamPass#1235]
Hello! 
I've installed the latest available version (2.1.25) of TeamPass and enabled the following settings:
*Authorize to have several folders with the same name. 	
*Authorize to have several items with the same name. 	
*Allow items with similar label in a common folder
* Enable importing data from CVS/KeyPass files 

Now I'm trying to import xml file from keepass which contains bunch of groups (server name), each group contains several items with the same title, but different usernames/passwords (title=ssh, user, password). 

Here I'm getting 2 problems:
1. I'm unable to import the the xml, but using  workaround from #1206 that problem is fixed
2. When the import is finished, in the folders I see only one item with title=ssh. It seems that all duplicates were ignored. 

Is there are any way to import all the items with duplicated titles?

P.S. thanks a lot for the great product!

**Comment by nilsteampassnet** [comment]
By design this was not possible.
I don't see any reason why I've set this limitation in the past.
I've removed this condition and will commit the change tonight.

You can make the manual modification in your current instance of Teampass without any impact on other features.
Take the changes done in file /sources/import.queries.php.
Remove condition if ($counter == 0) { at line 825
and else { } around line 908
