### ISSUE TITLE
[URGENT] Multiple Vulnerabilities in Teampass

### ISSUE THREAD

**Issue by pimps** [nilsteampassnet/TeamPass#1244]
Hi Nils,

First of all, thank you for creating the Teampass application, it is an awesome tool! 

One of the reasons we performed a security audit of this application is the company my team and I belong to is an information security team that specialises in penetration testing, however we were also looking at an application that provides functionality that Teampass provides. For this reason we decided to perform an in depth assessment of Teampass and discovered some critical issues that we believe should be addressed as soon as possible. Please see the findings below for the details: 
1. Blind SQL Injection (Critical)

We identified that the parameter sSortDir_0 in the file /teampass/sources/datatable/datatable.logs.php is vulnerable to a Blind SQL Injection via the ORDER BY sentence.

As PoC we inserted a SQL query asking if the name of the database is 'teampass' into the parameter sSortDir_0 if the answer of this question is true, the database will return 1 and the query will work normally. If the answer is false it will return multiple rows (select table_name from information_schema.tables) and the query will fail. Since the answer of this query is true, the functionality works as expected as you can see in the following screenshot:

<img width="1306" alt="blind-sqli_1" src="https://cloud.githubusercontent.com/assets/11393266/13939471/7ee7e0b2-f029-11e5-95a0-334bb9037d4e.png">

We repeated the same query but instead asking for an invalid name, in this case 'AA'. Since the answer of this query is false, the query fails and the application shows a verbose MySQL error (what is also a vulnerability... verbose error message):

<img width="1326" alt="blind-sqli_2" src="https://cloud.githubusercontent.com/assets/11393266/13939474/860254a4-f029-11e5-8934-9e4d2567e694.png">

We recommend changing all queries in the application to Prepared Statements. This is demonstrated in the following tutorial:

http://www.w3schools.com/php/php_mysql_prepared_statements.asp

Prepared Statements are designed to avoid SQL Injection vulnerabilities and is a solution to this problem. We also recommend avoid verbose error messages in the application.
1. Insecure File Upload (Critical)

We identified that the file upload and Profile Picture upload functionality have a flaw that allows a malicious user to upload malicious files to the server that may lead to the execution of arbitrary commands on the server, potentially leading to a full compromise of the server. The following screenshots illustrate this issue:

<img width="1251" alt="fileupload_1" src="https://cloud.githubusercontent.com/assets/11393266/13939480/94df19b2-f029-11e5-984a-5fc24e2c7d89.png">

<img width="713" alt="fileupload_2" src="https://cloud.githubusercontent.com/assets/11393266/13939485/9e25b314-f029-11e5-8b66-1b56497d3d7b.png">
1. Persistent XSS (High)

We identified that the application uses clientside JavaScript XSS filters. This design is flawed due to a malicious user simply intercepting the request with an HTTP Intercepting Proxy such as Burp Suite and removing the JavaScript filter for the application. The following screenshots demonstrate the XSS filters in the javascript code being removed through use of an HTTP intercepting proxy and including a normal XSS Payload:

<img width="407" alt="persistent_xss1" src="https://cloud.githubusercontent.com/assets/11393266/13939589/66120fa8-f02a-11e5-99c4-abed9d71a50f.png">

<img width="926" alt="persistent_xss2" src="https://cloud.githubusercontent.com/assets/11393266/13939594/6f6bc92c-f02a-11e5-9e12-303f4a7dd4d3.png">

The best protection against XSS is to perform Server Side user filtering and escaping the displaying of dynamic data using HTMLEncoding functionality. As such, we recommend implementing a Server Side XSS filter mechanism for all user inputs and applying the HTMLEncoding in all dynamic data that you show to the user.
1. Lack of CSRF protection in the application (High) (Need to confirm if current version is still vulnerable)

With this vulnerability attackers can force the user to perform actions that are unintended and without consent, by simply providing a valid session cookie. Several critical mechanisms of the application are vulnerable to this attack and include the following functionalities: Add New User, Edit User to Administrator and Change E-Mail. The Change E-mail is critical because after perform the CSRF attack, the attacker is able to use the recover password functionality in the application to hijack any user account.

---

We are still looking for more security issues in the application. If we find more we will report them here.

We hope this helps you in improving the security of you application and look forward to new versions of the application being released.

Regards,

Marcio Almeida
Senior Security Consultant at Securus Global a PS&C Group Company.

**Comment by yssvic** [comment]
Thanks for reporting this.

**Comment by nilsteampassnet** [comment]
Thanks Marcio for this depth analysis.

Of course I have some comments to it ;)

> Blind SQL Injection (Critical)
I think you found the last queries that were not protected. Indeed if I remember well in 2.1.24, I've made a lot of changes for SQL Injection after a big security analysis performed. SO now I think all my queries are protected. And of course, I'm using mysql prepared statements.
Please don't hesitate if you found any new one.

> Insecure File Upload (Critical)
This one is more "difficult" as I'm using a famous library for managing uploads.
I think here that it relies more on settings related to uploads. Indeed, you have the possibility to restrict the type of files that can be uploaded.
But in a general manner, file upload is always a hole in server security.
I will nevertheless take a look to the library's forum to check what could be done.

> Persistent XSS (High)
Correct, the example you shown was not protected. It is my mistake ... I'm always trying to protect the text fields and most of them are. I've added a small function to protect against html in text fields.

> Lack of CSRF protection in the application (High) (Need to confirm if current version is still vulnerable)
I've implemented CSRF Protector since 2.1.25. So I don't think you found an issue on 2.1.25 with this.

Please I'm always very interested in security feedback, so don't hesitate.

**Comment by twotwenty** [comment]
how have all these issues come along?
does teampass have a regular security audit ?

**Comment by nilsteampassnet** [comment]
All those have been fixed since 2.1.26
Many changes to fix security issues have been done.
CSRF protection was included, class for database checked and improved, forms sanitization, ...

Last analysis was performed by **Pang@ADLab of Venustech** on 2.1.27.3. Only 3 minor sql injections were found as managed outside the database class, and now fixed.

IF you watch the code (in the 20 last commits), you will see that most of the changes are related to good security practices.
