### ISSUE TITLE
TeamPass 2.1.25 / CentOS 7.2 / PHP 5.4.16

### ISSUE THREAD

**Issue by devinacosta** [nilsteampassnet/TeamPass#1255]
I installed the latest TeamPass onto a fresh CentOS 7.2 image, everything installed good, however when I go to the the main "information" page, i just get a message "loading data ... please wait" and it never goes beyond that. I tried to log into as other users same issue. 

I do see a few errors in the error_log for Apache. 

PHP Notice: Undefined variable: debug in /var/www/html/teampass/error.php on line 20
PHP Notice: Undefined index: session in /var/www/html/teampass/error.php on line 24
PHP Warning: fputs() expects parameter 1 to be resource, null given in /var/www/html/teampass/error.php on line 26.

Referrer is: http://url/teampass/index.php?page=manage_main

**Comment by nilsteampassnet** [comment]
Can you enable "Developper tools" in your browser and check the error sent by the server in the Console?

**Comment by bublboblz** [comment]
hi Devin, i experienced the same " "loading data ... please wait" issue on the main page. According to [this post](https://github.com/nilsteampassnet/TeamPass/issues/1036), teampass is not able to get information from teampass server (in my case could be due to our firewall rules) so I turned off the "Automatically load information about Teampass" in settings.

I still have the same notices and warnings in apache error_logs, but I don't think it's related to this feature.

Nils,
all i have in firefox console is that  should be preferred to « getPreventDefault() ». I use PHP 5.5.9-1ubuntu4.14 

Thank you

**Comment by Wrightie** [comment]
I'm experiencing the same issue, even if AFAIK there is no firewall rule blocking the communication between my Synology NAS and the TeamPass server... Got the "loading data ... please wait" message staying forever on my admin dashboard...
Thank you for fixing this :smile:
