### ISSUE TITLE
Decrypt passwords manually

### ISSUE THREAD

**Issue by imusmanmalik** [nilsteampassnet/TeamPass#1314]
Hi Nils,

First of all congrats for a great work and contributions from people.

I would like to know to find a way to be able to decrypt passwords manually as its one of the key things not to be dependent and to be able to restore in case of disasters etc.

I tried few things using the decrypt() function however unable to do so.

i also tried using the salt key on server so lets say

`echo "8QYR33E8kZqv5Q6lIM4ol8uSiq6vS3Y1+c+H9U6+GTpMzA6G75rJh53gDu/k1q+EBnqjHGRVy8ofSh799dy9ag==" | base64 -d | openssl aes-256-ecb -d -salt`

I am able to extract list of items and encrypted passwords using below query:

`select teampass_items.id, teampass_items.label, teampass_items.pw FROM teampass_items`

Can you please help point in right direction or how its encrypted? Like i think first using mcrypt + base64 + aes 256 cbc then salt ?

Thanks!

**Comment by nilsteampassnet** [comment]
Hello,

Thanks for this ;)

Concerning your request, it is mandatory to use the library that is used by Teampass which is curently PHPCrypt.
Do some retro-engineering on it to know exactely the commands to run.
Passwords are encoded using the SALT and the IV.

Now don't spend to much time on it because I will move to another library "PHP-Encryption" in next 2.1.27. Notice that this next release will be iso feature, only a (big) change for encryption security.

**Comment by 46Wil** [comment]
Thanks for the response Nils.  I did just that, and actually ended up writing a script to do the restore.  I have only been in the Linux world for about a week, and php even shorter than that.  I do have a little software engineering background though so hopefully I didn't butcher them too terribly.  The scanDir.php searches for filenames like "string", I thought it made it easier to search for backup files created by teampass that way.  I would like to include it in case it helps anyone else with their restore requirement.  I placed these files in the backup folder along with the script.backup.php.  Feel free to include them if you desire.
[script.restore.zip](https://github.com/nilsteampassnet/TeamPass/files/378468/script.restore.zip)

**Comment by pkoevesdi** [comment]
I have the same question: How can I decrypt single passwords I have in a database backup? 
I have the backup.sql and the teampass-seckey.txt . Is that all I need?
(Or: How can I reimport the items only from a database backup and the teampass-seckey.txt file? I don't want the whole database back, because I think it was defective.)
It' Teampass 2.1.27.10

**Comment by pkoevesdi** [comment]
The solution is in
https://github.com/nilsteampassnet/TeamPass/issues/848#issuecomment-355755985
