### ISSUE TITLE
Deleted all entries upon deleting personal folder

### ISSUE THREAD

**Issue by fgn-git-hub** [nilsteampassnet/TeamPass#1347]
### Teampass version: 2.1.23

I've created a new user with private folders activated.
When I realized there was a folder called "username", I tried to delete it. 
The result was that this folder seemed to be the root folder. 
Every entry has been deleted. 

I've recovered the nested_tree table from an old backup but this didn't helped either. 
Unfortunately the backup is too old to restore 100% of it. That would cause many password to be deleted

How could I recover this ?

**Comment by makhorkin** [comment]
I have confirm the issue. I think it's critical bug.

**Steps to reproduce**

1. Create a user
2. Enable the Personal folder feature for the user
3. Add Manager role to the user or set "Users are allowed to manage folders in allowed parent folders"
4. Login with the user's credentials
5. Select user's personal folder
6. Select "Delete a Folder"
7. Click "Delete"
8. Click "Ok"

**Expected behaviour**
Any action in Personal folder shouldn't affect any other folder. 
TeamPass should prevent deletion of any folder that hove one or more subfolders.

**Actual behaviour**
All folders for all users are deleted, except personal folder for that user. Also I think it issue was related , but I don't have steps to reproduce: sometimes ago after deleting some folders in user's personal folder all personal folders with all items for all users were dropped.

**Server configuration**

Operating system: Ubuntu 16.04 LTS (GNU/Linux 4.4.0-28-generic x86_64)

Web server: apache 2.4.18-2ubuntu3.1

Database: mariadb-server (10.0.25-0ubuntu0.16.04.1)

PHP version: (7.0.8-0ubuntu0.16.04.2)

Teampass version: Release 2.1.26 (14)

Updated from an older Teampass or fresh install: Updated from Release 2.1.26 (13)

**Client configuration**

Browser: Chrome 51.0.2704.103 m (64-bit)

Operating system: Windows 10.0.10586
