### ISSUE TITLE
Missing Restore Code

### ISSUE THREAD

**Issue by 46Wil** [nilsteampassnet/TeamPass#1392]
I recently installed the 2.1.26(13) and from what I can tell, there is actually no code behind the restore function being called just the select button to select your backup file, but it doesn't actually do anything with that backup file.  I went back each version to .21 and it doesn't look like any of them had an actual restore feature.  Am I misunderstanding the code?  Is this a future feature?  Is there a restore script lying around someplace that can be used?

**Comment by 46Wil** [comment]
I ended up writing a script to do the restore. I have only been in the Linux world for about a week, and php even shorter than that. I do have a little software engineering background though so hopefully I didn't butcher them too terribly. The scanDir.php searches for filenames like "string", I thought it made it easier to search for backup files created by teampass that way. I would like to include it in case it helps anyone else with their restore requirement. I placed these files in the backup folder along with the script.backup.php. Feel free to include them if you desire.
[script.restore.zip](https://github.com/nilsteampassnet/TeamPass/files/378478/script.restore.zip)

**Comment by nilsteampassnet** [comment]
It already exists inside ;)

There is an error in the DB, I will provide a fix next days.

**Comment by GagnonEric** [comment]
Hi,
Please, can you let me know where I can find/download and run the upgrade.php?
(requires to run upgrade.php)
I had to reinstall Teampass because my server crash and the server backup was not good, but I have a TeamPass backup, but can't restore them because it never finishes when the wheels start spinning.

Thanks
Eric

**Comment by GagnonEric** [comment]
My email egagnon@pavilioncorp.com

**Comment by nilsteampassnet** [comment]
Is this backup encrypted?
If it is not, then you can restore it through phpmyadmin or mysql command.
If it is encrypted then you must reinstall 2.1.26 version and restore through the restore feature.

**Comment by GagnonEric** [comment]
Yes it is encrypted
I reinstall 2.1.23, the original version and to test, I create 2 entry in Teampass, backup and try to restore and can't restore. I try to restore my original backup and can't restore.
Are you saying that I have to install 2.1.23, install 2,.1.26 and I will be able to restore?
Thanks
Eric

**Comment by GagnonEric** [comment]
Hi,

I tried to install the version 2.1.26 and 2.1.26-RC1 and in both case when I launch the web browser to start the initial configuration it hangs at the screen "Tables creation"
Please, can you tell me what can cause that?

I notice in the Database Connection screen, event if I enter a wrong account and/or password it sais "Connection is successful", that is strange.  What is causing that?

For ease of reinstalling, I use the account teampass_admin and password for the password.

FYI, before trying to re-install a new version, each time, I drop the teampass database using PHPAdmin to make sure I start fresh.

When I install the version previous version many time, I didn't encounter that kind of issue.

Thanks
Eric

**Comment by GagnonEric** [comment]
Hi Nils

Any help you can provide to reinstall the version 2.1.16, all my business password are missing because I can't restore from previous version of TeamPass due to the known bug.

Thanks
Eric

**Comment by nilsteampassnet** [comment]
> FYI, before trying to re-install a new version, each time, I drop the teampass database using PHPAdmin to make sure I start fresh.

This scares me.
You should not drop but upgrade Teampass.
By doing so you don't propagate the DB structural changes other your existing DB.
You cannot use a backup of an older version of Teampass.

A backup contains the structure of the DB corresponding to a version.
If you install a version using an older structure, then nothing will match.

**Comment by GagnonEric** [comment]
Thank you for that details.  The only reason why I was dropping the DB each time,  it is because it was empty and coming from the fact I had to reinstall Teampass from scratch, I lost the whole thing and my server backup restore didn't work. 
I understand your point and here what I plan to do and let me know if makes sense:
-Reinstall the original version 2.1.23 (from which I can't restore using Teampass due to a bug you fix in the version 2.1.26)
-Upgrade Teampass to the version 2.1.26 (upgrade the DB 2.1.23 to 2.1.26 by doing that)
-Restore the backup I made with TeamPass from the version 2.1.23 in my new version 2.1.26

From there I'm expecting to recover all business password.

Hopefully, this is the right path to take?

Thanks
Eric

**Comment by nilsteampassnet** [comment]
I'm pretty sure that restoring a DB done on 2.1.23 on a Teampass version 2.1.26 will not work as there have been a lot of structural changes in the DB between those 2 versions.

Backups are really important for any web application. I really recommend to perform daily backups of the DB using a cron. Teampass provides the script to be run to do so. Don't forget to put this in place once you will have manage your upgrade.

Now what is the bug id that I fixed in 2.1.26 and could help to restore your backup in 2.1.23?

**Comment by GagnonEric** [comment]
Hi Nils,

Long story short, I was not able to reply before you close this thread and unfortunately, I'm stuck with my recovery issue that is becoming critical.  You mention that you could connect to my system to try to help, is there a way we can arrange to get in touch?
You can reach me at egangon@pavilioncorp.com
Thanks
Eric

**Comment by GagnonEric** [comment]
Oops typo egagnon@pavilioncorp.com
