### ISSUE TITLE
LDAP authentication for multiple domain suffix

### ISSUE THREAD

**Issue by fjnalta** [nilsteampassnet/TeamPass#1410]
1. open LDAP settings
2. enter multiple domain suffix seperated with comma
3. try to login
### Expected behaviour

Specify multiple domain suffix and sperate them with a comma. (ex. @domain1.tld, @sth.local)

I would like to specify multiple domain suffix from LDAP because we have users which login with @domain1.tld and some users with @sth.local.
### Actual behaviour

It is not possible to enter multiple domain suffixes. If I enter "@domain1.tld, @sth.local" the LDAP authentication doesn' work at all. If I only specify one of them it works only for the users with this suffix.
### Server configuration

**Operating system:** Debian 8.5
**Web server:** Apache 2.4.10
**Database:** MySQL-Server 5.5.50
**PHP version:** 5.6.24
**Teampass version:** 2.1.25 
**Updated from an older Teampass or fresh install:** fresh
### Client configuration

**Browser:** Chrome 52.0.2743.82 m (64-bit)
**Operating system:** Windows10

**Comment by mweber88** [comment]
While I do foresee this being possible, it's challenging for sure.  If you think about it, LDAP would have to attempt a bind to each suffix you supply to authenticate.  If you have, say, 5 different domain suffixes for your organization, it would perform the attempted bind to LDAP 5 times.

In looking at the PHP library for AD manipulation, the domain suffix is a string value, not an array.  Therefore, it cannot take multiple values.

Since users have different domain suffixes, they therefore should enter their appropriate domain suffix for login, and you leave the domain suffix field blank.  It may not be the easiest for the users, but based on your environment, it's the most functional for the servers, and that's probably what the library authors intended.

**Comment by fjnalta** [comment]
Thanks for the answer.

We managed already to get it work as good as possible. We specified just one DN-Suffix. AD users with this suffix can login normally while the others have to write the domain name as a prefix and login just with the username. e.g. DOMAIN\username

This works well enough for us.
