### ISSUE TITLE
One time view link with - Item will not be automatically deleted when accessed through otv option enabled

### ISSUE THREAD

**Issue by Aggerone** [nilsteampassnet/TeamPass#1421]
### Steps to reproduce
1. On a item, enable / tag: Item will be automatically deleted after being seen  
 times.  or after date on Password & Visiblity tab. 
2. Set it to 1 times
3. Save
4. Click on item menu, One time view link, copy
5. Try the link in another browser, it works unlimited number of times, it will not be deleted
6. And even when I use a logged in user, and view it, the item is removed after over 1 view. 
7. The link still works, event when no items is visible in the Folder.

### Expected behaviour
The one time view links should work the number of times that is set in the Item will be automatically deleted after being seen  
 times box.

### Actual behaviour
Se steps to reproduce

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
nginx
**Database:**
mysql

**PHP version:**
php 5.6
**Teampass version:** 
2.1.26.5
**Updated from an older Teampass or fresh install:**

### Client configuration
**Browser:**
any
**Operating system:**
any

**Comment by nilsteampassnet** [comment]
Sorry for long time to answer.

The situation is normal concerning the fact that OTV is not considered in the view counter. So by design, what you describe is normal. I could indeed change this.

For the 2d behavior you describe concerning the unlimited number of OTV views has been corrected in a 2.1.26 package after 2.1.26.5 ... I've done several tries and it works as it should.

**Comment by Aggerone** [comment]
Nice.  Thank you :)
