### ISSUE TITLE
Login with LDAP/AD must have DOMAIN/user

### ISSUE THREAD

**Issue by crouch766** [nilsteampassnet/TeamPass#1424]
### Steps to reproduce
1. Setup login with LDAP
2. try to login with 'user' -> AD password: FAIL
   3.try to login with 'DOMAIN\user' -> AD Password: Success
### Expected behaviour

With the previous release the username used for AD Login was only the sAMAccountName of the AD User
### Actual behaviour

With the new version i must use 'domain\username' for log me in into teampass
### Server configuration

**Operating system**:
Ubuntu 16.04.1 LTS
**Web server:**
Apache/2.4.18 (Ubuntu)
**Database:**
mysql  Ver 14.14 Distrib 5.7.13, for Linux (x86_64) using  EditLine wrapper
**PHP version:**
PHP 7.0.8-0ubuntu0.16.04.2
**Teampass version:** 
TeamPass 2.1.26 
**Updated from an older Teampass or fresh install:**
fresh install
### Client configuration

**Browser:**
Chrome 52.0.2743.116
**Operating system:**
Windows 10

Thanks for the support,
Regards,
Stefano

**Comment by WojTecH94** [comment]
Same here, but I have 1 user which can login without "DOMAIN\"

**Comment by jahantech** [comment]
Had the same issue so I changed the code so that login field prepopulates the domain name for me. But I agree, i was hoping to provide the samAccountName to login but that didnt work without the domain prefix.

**Comment by mweber88** [comment]
All--

I have two questions:

1.  Do you have the LDAP settings set to Windows/Active directory, or to one of the Posix variants?

2.  Do you have a Domain Suffix specified in the LDAP config?

I have found one problem in that the saved LDAP settings in includes/config/tp.config.php may have the ldap_type value set to '0' rather than 'windows' which will also require a domain suffix to be entered on the username line.  If you check this settings file and it shows the value as '0' instead of 'windows' (provided you are intending to use Windows/Active Directory and not a Posix variant), you can fix this by changing to a Posix variant, waiting for the checkmark to indicate it has been updated, then changing it back.  Then, log out and back in to see if it has changed anything for you.

The logic requires a domain suffix and will either take what is provided in the case of the DOMAIN\Username, being the domain preceding the \ and append that to username@ before attempting to use it, or if DOMAIN\Username isn't used, and the setting is windows/active directory, it will use the domain suffix provided in the settings.  If one doesn't exist, it will not work with the current Active Directory libraries used.  It MAY work with a newer version of the library as it attempts to determine the domain suffix from Active Directory, but I can only see it being problematic at best if you have either multiple domains in your Active Directory forest or you use an alternative domain suffix for your users (i.e. domain is domain2.domain1.tld, whereas users are user@domain1.tld).  The latter case could be in use to make sure userids and global email addresses are the same.

Hope this helps.

Mike

**Comment by x-men222** [comment]
Excatly same Problem here.   
@jahantech  Can you tell us where you canged the Code ?
