### ISSUE TITLE
I am new to teampass and having trouble on how to test LDAP connection for version 2.1.26.  I have followed the steps on this link: http://www.bauer-power.net/2014/03/how-to-get-ldap-working-in-teampass.html#.V7PgaJh97IU. Is there a way to test if the LDAP connection is successful?

### ISSUE THREAD

**Issue by abvillanueva** [nilsteampassnet/TeamPass#1429]
### Steps to reproduce

1.
2.
3.
### Expected behaviour

Tell us what should happen
### Actual behaviour

Tell us what happens instead
### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Teampass version:** 

**Updated from an older Teampass or fresh install:**
### Client configuration

**Browser:**

**Operating system:**
#### Web server error log

```
Insert your webserver log here
```
#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))

```
Insert the Firebug log here
```

**Comment by andreyoc** [comment]
I'm using this post because looks like more with my problem: ldap don't work.

Steps to reproduce

1. type user
2. type password
3. enter

Expected behaviour

create a user and login using ldap

Actual behaviour

Do nothing. show this message:
(Login credentials do not correspond!)

Server configuration

Operating system: CentOS release 6.8 (Final)

Web server: httpd-2.2.15-54.el6.centos.x86_64

Database: php55u-mysqlnd-5.5.38-1.ius.centos6.x86_64

PHP version: php55u-5.5.38-1.ius.centos6.x86_64

Teampass version: TeamPass 2.1.26

Fresh install

Client configuration

Browser: firefox 48.0.2

Operating system: windows 10

Logs
Web server error log

ssl_error_log:
(nothing)
error_log:
(nothing)
ssl_access_log: 
("GET /teampass/includes/js/jquery-ui/images/ui-bg_inset-hard_75_999999_1x100.png HTTP/1.1" 200 253
"POST /teampass/sources/identify.php HTTP/1.1" 200 42)
access_log:
("GET /teampass/includes/js/jquery-ui/images/ui-bg_inset-hard_75_999999_1x100.png HTTP/1.1" 200 253
"POST /teampass/sources/identify.php HTTP/1.1" 200 42)

Firebug log (How to?)

The link is broken

CONCLUSION:
I did the same steps using a 2.1.25 version and it works fine.
Using the 2.1.26 do not work.
I have no clues because the log file shows me nothing.
