### ISSUE TITLE
Impossible to copy to clipboard from Safari

### ISSUE THREAD

**Issue by Franckboby** [nilsteampassnet/TeamPass#1430]
### Steps to reproduce
1. Connect to Teampass with Safari
2. Try to copy to clipboard a password
### Expected behaviour

Password is normally copied in the clipboard,
A pop-up appear to confirm that.
### Actual behaviour

Nothing happen, the password is not copied and we don't get the pop-up.
### Server configuration

**Operating system**:
Ubuntu 14.04.4 - amd64

**Web server:**
Apache 2.4.7

**Database:**
Mysql 5.5.50

**PHP version:**
5.5.9

**Teampass version:** 
2.1.26

**Updated from an older Teampass or fresh install:**
From fresh install
### Client configuration

**Browser:**
Safari v9.1.2 (11601.7.7)

**Operating system:**
OSX El Capitan v10.11.6
### Logs

Nothing usefull, no entry logs when I try to clic on the copy top clipboard option.

**Comment by giannakopoulosj** [comment]
Same here on Firefox
Firefox version
![image](https://cloud.githubusercontent.com/assets/2518387/18081089/9becd738-6e98-11e6-8621-a6e961a7642b.png)
OS Version: Windows7
ServerOS: Red Hat Enterprise Linux Server release 6.5 (Santiago)
SQL v.: Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503
ServerApp: Apache/2.2.15 (Red Hat)
Teampass Version: Release 2.1.26 (17)

**Comment by nilsteampassnet** [comment]
Clipboard copy is ensured using [clipboard.js library](https://clipboardjs.com/).
But logically it should be compliant with the version of your browsers.

You can perhaps try to use the unminified version of the file.

**Comment by giannakopoulosj** [comment]
Thank you Nils. Based on the clipboard.js link you provided the initial failure i had was due:
Firefox: The version v.38 is not supported.
Chrome: Was above the need version as resault no problem was reported there.
Safari is not supported quoting from link:

> 
Although copy/cut operations with execCommand aren't supported on Safari yet (including mobile), it gracefully degrades because Selection is supported.
> 
That means you can show a tooltip saying Copied! when success event is called and Press Ctrl+C to copy when error event is called because the text is already selected.
> 
For a live demonstration, open this site on Safari.
