### ISSUE TITLE
[Help] versioncheck for Teampass

### ISSUE THREAD

**Issue by OptimusOS** [nilsteampassnet/TeamPass#1434]
Hi Guys,
thx for a great tool. I have a question:

I will write a script for automatic upgrade and for this one i need a version.  
Which file can i used for check the Teampass Version?
i dont can you the Changelog than something is missing the last number off this change 
Thanks

**Comment by mweber88** [comment]
There are several ways that I can see.  First, if you can write a script to dig into the mysql Teampass database, the table "teampass_misc" has it.

select valeur from teampass_misc where intitule = 'cpassman_version';

Or, if you're after files only, the index.php file in the teampass root directory has a comment line in the beginning which states the version:

 * @version       2.1.26

I'm sure if you're writing scripts, you can write one that will grep the @version line, strip out the white space and other cruft and leave you with your version number.

HTH,
Mike

**Comment by qubez** [comment]
Unfortunately even the minor version number is not currently reliable to determine if a simple file-replacement upgrade is possible. There have been many commits made into 2.1.26; master is now up to 2.1.26 (17). 

Tag 2.1.26 (15) made a database change that will require the upgrade.php script to be run against any previous installs. This wasted a few hours of my time debugging my own forks.

Hopefully future database changes will be reserved for major releases, with a bit of beta testing done first. In other projects, we expect Master be kept as a stable release (because that is what a new user would download), and upgrade procedures noted in release notes.

**Comment by nilsteampassnet** [comment]
I will take your comments into account.

Thinking also on solving your evolution "criteria".
