### ISSUE TITLE
Password Items Labels do not preserve the '\' character

### ISSUE THREAD

**Issue by 46Wil** [nilsteampassnet/TeamPass#1445]
### Steps to reproduce
1. **+ Add item**
2. Enter a _Label :_ name, be sure to include the '\' character.
3. Enter a password that meets the password requirements.
4. Select **Save**

### Expected behaviour
When a new password item is saved that contains the '\' character the PW list should display the label with the '\' character.

### Actual behaviour
Instead it actually saves the '\' character as &#92;.  The '\' character is preserved in usernames, but not for the label.

### Server configuration
**Operating system**:
Teampass Server: CentOS 7

**Web server:**
Apache/2.4/6 (CentOS)

**Database:**
5.5.50-MariaDB

**PHP version:**
5.6.24

**Teampass version:** 
2.1.26 (15)

**Updated from an older Teampass or fresh install:**

### Client configuration
Chrome: 52.0.2743.116 m (64-bit)

**Operating system:**
Client: Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

P.S.  Behavior is misspelled above.  Might want to correct the template.

**Comment by qubez** [comment]
The github bug report system seems to have stripped out the character in question. It only shows the backslash (0x5c) character. Can you describe the character, perhaps referring to the code number from:
http://www.december.com/html/spec/codes.html
or http://www.ebyte.it/library/educards/html/HTMLEntitiesAndGlyphs.html

**Comment by qubez** [comment]
meekrodb in TeamPass is several commits behind that project. There are several changes worth merging to the customized version of db.class.php in teampass, like https://github.com/SergeyTsalkov/meekrodb/commit/da46a1eacc683b34fcbba069c1f25f6930fbb9c9

Some deal with string encoding and decoding, and may correctly store protected characters, fixing bugs like this. Unit tests would need to confirm that no existing passwords are ever returned incorrectly.

The error logging hacks inserted into db.class.php could be moved into a parent wrapper function, so that meekrodb can stay updated.

**Comment by 46Wil** [comment]
That is correct, it is the backslash, "&#92; \ Reverse solidus (backslash)", but it only has issues on the Label.  It doesn't have issues in the password or in the username.

**Comment by qubez** [comment]
The problem is bad and inconsistent encoding and decoding, specifically double-sanitizing html entities.

putting `aaaa\aaaa` into the label field stores this in the database: `aaaa&amp;#92;aaaa` - however bbbb\bbbb in the description field stores `bbbb&#92;bbbb` in the database.

replacing the database label with one encoded like the description fixes everywhere except when editing the label, which shows semi-sanitized output - it removes amp; but not the #92;

I'll see if i can work up a fix that will be compatible with any previously stored labels (or at least not make them worse).

**Comment by nilsteampassnet** [comment]
> The doctype should be ENT_XHTML, and the fourth parameter double_encode should be set to false, for starters. Elsewhere reversing the encoding is done inconsistently.

Yes absolutely, thank you for this tip.

I really appreciate all the help you provide on this project.
