### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by cgkelleher** [nilsteampassnet/TeamPass#1465]
This is not really an issue but can functionality be added to enable more than one password to be stored per entry. 

This would be beneficial for things like network switches which have more than one password?

**Comment by qubez** [comment]
There is a feature to add custom fields to items. While they won't be masked or strength-checked, passwords can be stored in these and they will be encrypted in the database and only accessible to those who can access the password item in which they are stored.

To enable and use:
1. Create a category in the category area of admin, such as "alternate logins"
2. Create custom fields in that category - (+) icon, such as "second username", "second password"
3. In the customize tab of admin, select "Authorize Items to be completed with more Fields (by Categories)" 
4. When a user logs in again, there will be a new fourth tab "more" when adding or editing password items that will allow you put values in these new fields. They will be displayed at the bottom of the password display area.

I have a better translation for this option, since it is not very discoverable otherwise:
    **'settings_item_extra_fields' =>** 'Custom item fields enabled',
    **'settings_item_extra_fields_tip' =>** 'Enables another tab when editing items, allowing custom fields for user data entry. Admin must first create categories and the custom field labels to be displayed in the categories. This feature consumes more server resources.',

**Comment by nilsteampassnet** [comment]
@qubez, interesting proposal concerning the rewording of categories.

I do agree that it could be more clear.

**Comment by qubez** [comment]
In the big translation I'm working on I've made such changes:
TeamPass Settings -> Settings
Customize -> Options
Specific Actions -> Tasks
Emails -> Email
Categories -> Custom Folders
Views -> Utilities (or maybe Maintenance)

One would have to modify documentation after such a change, but luckily there's not much documentation. Better tooltips would refer to the correct section (like "You must run the _create user personal folders_ task on the _task_ tab after enabling the personal folder feature")  

I would move LDAP and two-factor to the same tab "Authentication", but that is modification beyond the language files.
