### ISSUE TITLE
Install RE-Install Teampass not moving out of portal

### ISSUE THREAD

**Issue by zalexxx** [nilsteampassnet/TeamPass#1493]
### Steps to reproduce
1. We had installed 2.1.20 2.1.21 2.1.26 and the result is a portal connection without other thing
   2.
   3.
### Expected behaviour

NOTHING
### Actual behaviour

Is anyboby have the same trouble, installation without problem and when I want to connect nothing else Please identify yourself.
FRESH INSTALL
### Server configuration

**Operating system**: DEBIAN 8 PLESK 12.5

**Web server:** APACHE2.4.10

**Database:** MARIADB 10.0.26

**PHP version:** 5.6.24 also test with 7.0.6

**Teampass version:** 2.1.26 - 2.1.26.19 - 2.1.20 - 2.1.21

**Updated from an older Teampass or fresh install:** non fresh install
### Client configuration

**Browser:** Chrome Safari Firefox IE 11 IE edge

**Operating system:** WIN 10 WIN 7 OSX 10.11.6
#### Web server error log

```
NO LOG in PHP APACHE...

```
#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))

```
Hacking attempt...
```

**Comment by qubez** [comment]
You likely need to configure the URL in csrfp config file correctly to the site. There is a sample file in the install at `includes\libraries\csrfp\libs\csrfp.config.sample.php`, and if you have run the install procedure, you should have a version with your own site URL at `includes\libraries\csrfp\libs\csrfp.config.sample.php`. The cross-site attack prevention is what gives the "hacking attempt" error if it is misconfigured.

You must start a fresh install by running `http://URL/install/install.php` to set up Teampass, or if you already were using teampass, you must run `http://URL/install/upgrade.php` to update settings and config files. (URL is your permanent web site domain name).

If you are upgrading, be sure to delete the /install directory after you have everything working.

**Comment by zalexxx** [comment]
Thanks for your reply, I have found something else, when I change the language with the flag in up right corner nothing happen.
So what do you mean about 'misconfigured' everythhing was good in installation.
When I make an upgrade I cannot I have this message 
The upgrader will now update the database by running several upgrade scripts.
An error occurred. Please check and relaunch.
11:31:57 - ERROR: MySQL Error!
11:31:57 - upgrade_run_db_original.php - Loop #1 
[{"finish":"0", "scriptname":"upgrade_run_db_original.php", "parameter":""}]
[{"finish":"1", "msg":"", "error":"MySQL Error! "}]
Thanks again for all.

**Comment by qubez** [comment]
The language setting flag in upper right is a user-specific setting. Selection is unreliable though - I've selected Chinese and seen Bulgarian...  Try user log off and log back on after selecting the user language.

The default language is set by admin. You will find an option on the administrator's _settings_ tab to change they system language.

**includes\libraries\csrfp\libs\csrfp.config.php** should have this line with your site's name:

`   "jsUrl" => "http://FULLDOMAIN.com/includes/libraries/csrfp/js/csrfprotector.js",`

Unfortunately, the value on this line is set when you install and is not upgraded. You may need to edit the file and change this line. If you were using an IP address instead of name when you installed, for example, it may be set wrong, and cause the "hacking attempt" errors. If you use HTTPS, this line also needs to say https.

You say "fresh install" in your bug report, but you also say "We had installed 2.1.20 2.1.21 2.1.26", which sounds like you are upgrading. I will test to see if I can find a problem going from 2.1.20 -> 2.1.26.

**Comment by zalexxx** [comment]
thanks for your reply.
I had change, in csrfp.config.php
jsUrl (to the good one, to test I cut and paste in navigator) and I change jsPath to the real absolute path.
The problem is the same.
Actually I am testing the 2.1.26 fresh git download (https://github.com/nilsteampassnet/TeamPass.git).
I will test your upgrade solution and I'll say you what is the result very soonly.
Thanks again!!!
Regards

**Comment by zalexxx** [comment]
Sorry but I cannot install the 2.1.21 cannot add table (failled)
Is there any good version without trouble?
There is so much bugs, had you patch these problems?
Thanks again for your reply.
Regards
PS: do you make an require list and compatibility version of dependence
I try the 2.1.27 (same result Hacking attempt...)

**Comment by qubez** [comment]
It seems like you are missing something. Did you give the database user full access to your database, for example? Teampass works fine. It is much easier to get set up than other complex web applications like tWiki on perl.

**Comment by zalexxx** [comment]
I will test Wiki tomorrow. But I have 5 instances with our own code app; and 1 WORDPRESS.
All working fine...
Tomorrow wil be a better day.
Thanks again.
Regards

**Comment by qubez** [comment]
(PS don't test tWiki unless you need a wiki site, it's way too much work)
