### ISSUE TITLE
Is it possible anyhow to use LDAP filters for AD?

### ISSUE THREAD

**Issue by misterunknown** [nilsteampassnet/TeamPass#1495]
Hi,

is it possible to use LDAP filters for Active Directory servers anyhow?

Cheers,
Marco

**Comment by nilsteampassnet** [comment]
Personally I can't answer this question ... you know how bad I am concerning AD things ;)

**Comment by mweber88** [comment]
Marco--

Can you explain?  I can try to answer this for you as I'm familiar with Active Directory LDAP and the included library for authentication in Teampass.

Mike

**Comment by misterunknown** [comment]
Hey Nils and Mike,

I would like to use ldap filters like that:

    (&(objectCategory=person)(objectClass=user))

With such expressions we could filter for several groups or other criteria within our AD. Just limiting users by a base DN is not really sufficient for our AD structure.

Thanks for your help!

Cheers,
Marco

**Comment by mweber88** [comment]
Marco—

In researching the parts of the libraries used for LDAP, it has no way of using a search string for filtering results.

I’m still not understanding the issue behind what you want to do, so if you want to take this offline and email me directly so we can discuss, I’m open to that.  However, I’m going to recommend to Nils to close this since there is no possibility in the LDAP libraries.

Nils—

Since there is no way of doing this in the LDAP libraries, I recommend closing this issue.

Mike
mweberjunk01 —AT-- gmail —DOT-- com

**Comment by nilsteampassnet** [comment]
Ok thanks
