### ISSUE TITLE
Some items have clones

### ISSUE THREAD

**Issue by reginfo** [nilsteampassnet/TeamPass#1523]
Today I found out that for item I see clone of it. When I try to click on cloned item it selects original item (I beleive so). 
And I do not know how to remove it.

Link to video located on Youtube.
https://youtu.be/a7hRSEFCrlY
### Steps to reproduce

Really do not now how to reproduce. I only figure it out some times ago.
### Server configuration

**Operating system**:
Ubuntu 16.04.1
**Web server:**
Apache/2.4.18 (Ubuntu)
**Database:**
Ver 14.14 Distrib 5.7.15
**PHP version:**
PHP 7.0.8-0ubuntu0.16.04.2 (cli) ( NTS )
**Teampass version:** 
2.1.26.20
**Updated from an older Teampass or fresh install:**
Updated from 2.1.26.18
### Client configuration

**Browser:**
IE11, FF
**Operating system:**
Windows 10 Ent x64

**Comment by nilsteampassnet** [comment]
I've managed to reproduced when the browser size has a small height and that the list of items contained in the folder makes it exact height... my sentence is not clear but I don't really know how to formulate.

I think I will not correct it because 2.2 will be a change of design (in 2017), and here a fix will take time.
