### ISSUE TITLE
Password complexity levels?

### ISSUE THREAD

**Issue by TheKingKai** [nilsteampassnet/TeamPass#1535]
Ok, I read Issue #1458. But I still don't know the difference and requirements for password complexity levels. Can anyone explain these requirements to me?

@tehnotronic

**Comment by qubez** [comment]
That plugin doesn't document exactly what the rules are either, you have to read the code. Since it returns a score based on password length and modified by the password complexity, it would be hard to specify a single thing that makes a password "very strong". One rule is that all lower-case will be "very weak" regardless of length. It has some other checks for repeated words and other factors that also lower the score if detected.

Better than all these confusing levels in TeamPass would be to have a single admin-customizable policy for strong passwords, specifying how many upper/number/symbols are requiredto be qualified as a "strong" password. I doubt anybody needs all these levels anyway, just an "enforce system password policy?" checkbox on folders would be sufficient to ensure strong passwords on items that need protection against dumb users.

A word list and many AI tests would better predict strength and hack-resistance.
 _qzvioeuftuawivh_ would be stronger than _applebananaorange_, for example. However, sending a wordlist to the client's javascript is impractical; a server-side password check method would be required.


The other annoyance is that the password generator should automatically generate passwords that meet the requirements, but the generator code doesn't understand the password tests either.
