### ISSUE TITLE
SSH passphrase lost after folder move

### ISSUE THREAD

**Issue by gerbsen** [nilsteampassnet/TeamPass#1581]
Hello,
We just noticed a bug in Teampass where the SSH Keys/Passphrases were missing after we moved a folder with an item with this field.

Cheers,
Daniel

![screenshot 2016-11-22 11 54 52](https://cloud.githubusercontent.com/assets/1186245/20521298/dd2b10c6-b0aa-11e6-9e71-1c410b8b563c.png)

**Comment by abenrob** [comment]
If the target folder was not in the settings>categories>associated folders for the custom category, the custom category is lost completely upon move. Even if the parent of the target folder is in the associated folders list...
Would be extremely useful to notify a user when moving something that the target folder does not support the custom field.
Additionally, when selecting associated tables, the select list does not retain previous selections, which when managing several dozen folders becomes dangerous - especially since we see that a field is lost completely on schema mismatch.

**Comment by nilsteampassnet** [comment]
Something is not logical here.
I did the test and as I expected the "custom fields" are "moved" with the folder.

Indeed by design the custom fields are attached to the folder id. So by moving the folder it doesn't change its id and the customer fields are moved too.
I've done several tests in several configurations and couldn't find an issue.

So there must be a setting you have that you didn't wrote here.
Perhaps could you give all settings on your concrete case so that I will try to reproduce.

**Comment by abenrob** [comment]
Thanks @nilsteampassnet. In our case, the item was moved from one folder INTO a new folder at the same level (so we can grant access to each item). So the folder was not moved, just the item. The new folder (a child of the original folder) was not _manually added_ to the list of associated folders, so the field was lost on move.

```
folder.servername (in associated folders)
┗━ item.root
┗━ item.user
```
became:
```
folder.servername (in associated folders)
┗━ folder.root (NOT in associated folders)
   ┗━ item.root
┗━ folder.user (NOT in associated folders)
   ┗━ item.user	
```

So it seems like adding a folder to a folder which is in the associated folders should _**inherit**_ the schema (as opposed to manually re-selecting **every single folder we ever want to have this field...**)

**Comment by nilsteampassnet** [comment]
OK understood.

I will provide the fix tomorrow.

**Comment by nilsteampassnet** [comment]
Can you please indicate if the fix corrects your point, and if the way it is working seems ok for you?

**Comment by abenrob** [comment]
I will check it out on Monday. Thanks!

**Comment by abenrob** [comment]
So we updated our teampass, and I tried this out today...
I created a new folder as a _child folder_ of one with the custom field. This folder does not inherit the schema of the parent, nor can I bulk-add the custom field to folders (to include the new folder).

Perhaps you can outline what specifically the fix was supposed to do, so I can confirm the actual functionality?

Thanks.
