### ISSUE TITLE
DomainException after update from 2.1.15 to 2.1.26-final-3.

### ISSUE THREAD

**Issue by pedrohc** [nilsteampassnet/TeamPass#1629]
### Steps to reproduce
1. Update teampass from version 2.1.15 to 2.1.26-Final-3
2. Try to log in from an ldap account.

### Expected behaviour
Should log in without any problems.

### Actual behaviour
Getting the error below after trying to login with an ldap account.

[Wed Jan 18 14:31:18.573354 2017] [:error] [pid 2408] [client 127.0.0.1:54613] PHP Fatal error:  Uncaught exception 'DomainException' with message 'Unsupported Password Hash Supplied' in /var/www/teampass/teampass/includes/libraries/PasswordLib/Password/Factory.php:87\nStack trace:\n#0 /var/www/teampass/teampass/includes/libraries/PasswordLib/PasswordLib.php(78): PasswordLib\\Password\\Factory->verifyHash('XXXXXXXXX', 'ghwiqour243f32dvh...')\n#1 /var/www/teampass/teampass/sources/identify.php(515): PasswordLib\\PasswordLib->verifyPasswordHash('XXXXXXXXXXX', 'zghwiqour243f32dvh...')\n#2 /var/www/teampass/teampass/sources/identify.php(87): identifyUser('ZfedwAFGIWadswq32dAD/dw...')\n#3 {main}\n  thrown in /var/www/teampass/teampass/includes/libraries/PasswordLib/Password/Factory.php on line 87, referer: http://teampass.here/index.php?page=items

### Server configuration
**Operating system**:
Linux Debian 8
**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
5.6.29-0
**Teampass version:** 
2.1.26-final-3
**Updated from an older Teampass or fresh install:**
Updated from version 2.1.15
### Client configuration
**Browser:**
Firefox

### Logs

[Wed Jan 18 14:31:18.573354 2017] [:error] [pid 2408] [client 127.0.0.1:54613] PHP Fatal error:  Uncaught exception 'DomainException' with message 'Unsupported Password Hash Supplied' in /var/www/teampass/teampass/includes/libraries/PasswordLib/Password/Factory.php:87\nStack trace:\n#0 /var/www/teampass/teampass/includes/libraries/PasswordLib/PasswordLib.php(78): PasswordLib\\Password\\Factory->verifyHash('XXXXXXXXX', 'ghwiqour243f32dvh...')\n#1 /var/www/teampass/teampass/sources/identify.php(515): PasswordLib\\PasswordLib->verifyPasswordHash('XXXXXXXXXXX', 'zghwiqour243f32dvh...')\n#2 /var/www/teampass/teampass/sources/identify.php(87): identifyUser('ZfedwAFGIWadswq32dAD/dw...')\n#3 {main}\n  thrown in /var/www/teampass/teampass/includes/libraries/PasswordLib/Password/Factory.php on line 87, referer: http://teampass.here/index.php?page=items

**Comment by nilsteampassnet** [comment]
in 2.1.17, the users pwd encryption library has changed.
That's why there are some conversion commands during the authentication.
So I don't understand why you get this error.
It clearly indicates that the hash is not at expected format, which means the conversion is not performed.

To investigate, either you should debug what is happening with your data between line 
`if ($proceedIdentification === true && $user_initial_creation_through_ldap == false) {`
and
`if ($pwdlib->verifyPasswordHash($passwordClear, $data['pw']) === true) {`

or you should provide me an access.

**Comment by pedrohc** [comment]
Well, I can't give you access.
Any tips on how to debug it?

**Comment by nilsteampassnet** [comment]
Can you change the code 
`
        //v2.1.17 -> change encryption for users password
        if (
                $passwordOldEncryption == $data['pw'] &&
                !empty($data['pw'])
        ) {
            //update user's password
            $data['pw'] = bCrypt($passwordClear, COST);
            DB::update(
                prefix_table('users'),
                array(
                    'pw' => $data['pw']
                ),
                "id=%i",
                $data['id']
            );
        }
        if (crypt($passwordClear, $data['pw']) == $data['pw'] && !empty($data['pw'])) {
            //update user's password
            $data['pw'] = $pwdlib->createPasswordHash($passwordClear);
            DB::update(
                prefix_table('users'),
                array(
                    'pw' => $data['pw']
                ),
                "id=%i",
                $data['id']
            );
        }
`

with this

`
echo "$passwordOldEncryption: ".$passwordOldEncryption." -- $data['pw']: ".$data['pw']." -- ";
        //v2.1.17 -> change encryption for users password
        if (
                $passwordOldEncryption == $data['pw'] &&
                !empty($data['pw'])
        ) {
			echo "In 1st IF condition -- ";
            //update user's password
            $data['pw'] = bCrypt($passwordClear, COST);
            DB::update(
                prefix_table('users'),
                array(
                    'pw' => $data['pw']
                ),
                "id=%i",
                $data['id']
            );
			echo "New $data['pw']: ".$data['pw']." -- ";
        }
		echo "$passwordClear: ".$passwordClear." -- Crypt result: ".crypt($passwordClear, $data['pw'])." -- ";
        if (crypt($passwordClear, $data['pw']) == $data['pw'] && !empty($data['pw'])) {
            //update user's password
            $data['pw'] = $pwdlib->createPasswordHash($passwordClear);
            DB::update(
                prefix_table('users'),
                array(
                    'pw' => $data['pw']
                ),
                "id=%i",
                $data['id']
            );
        }
`

**Comment by italovalcy** [comment]
Hello guys,

I could  reproduce the same issue after upgrade to 2.1.26-Final-3 and using auth based on LDAP.

Another way  to  debug this is to enable the debug flag on identity.php such as:
```
$debugLdap = 1; //Can be used in order to debug LDAP authentication
```

And then look for LDAP information in /path/to/teampass/files/ldap.debug.txt

Particularly, what seems to cause this issue is the addition of "ldap_type" new parameter, which seems to be configured to "0" as default  per upgrade_run_db_original.php. However, the value for this parameter should  be one of: windows, posix, posix-search. In my case, the ldap suffix was guessed wrong.

After fix this on database, I could log in without problems.

Maybe I would be interesting try to guess the ldap_type based on current parameters from old install in upgrade script. For instance:
 - if you have ldap_suffix which looks like "@something" it would be 'windows', else 'posix' or 'posixx-seach'
 - if you have binddn/bindpw, it would be 'posix-search'; else it is probably 'posix'

Or even ask for LDAP type along upgrade.php steps.

Regards, Italo
