### ISSUE TITLE
All items say Can't encrypt password after upgrade from .26.2 to .27.0

### ISSUE THREAD

**Issue by ImNtReal** [nilsteampassnet/TeamPass#1657]
### Steps to reproduce
1. Upgrade from 2.1.26.2 to 2.1.27.0
2. Log in as a regular user
3. List items in a folder

### Expected behaviour
Items should be there, with passwords available

### Actual behaviour
All items say can't encrypt password, and have no password

### Server configuration
**Operating system**: CentOS 7

**Web server:** Apache 2.4.6

**Database:** MariaDB 10.0.29

**PHP version:** 7.0.16

**Teampass version:** 2.1.27.0

**Updated from an older Teampass or fresh install:** Updated from 2.1.26.2

### Client configuration
**Browser:** Firefox 51.0.1

**Operating system:** Arch Linux

#### Web server error log
```
[Mon Feb 27 14:44:25.619085 2017] [:error] [pid 56575] [client 172.20.69.68:60474] PHP Warning:  session_start(): Failed to decode session object. Session has been destroyed in /var/www/TeamPass-2.1.27.0/logout.php on line 16, referer: https://vmasteampasst01.nghs.com/index.php?page=items
[Mon Feb 27 14:44:25.619177 2017] [:error] [pid 56575] [client 172.20.69.68:60474] PHP Warning:  session_destroy(): Trying to destroy uninitialized session in /var/www/TeamPass-2.1.27.0/logout.php on line 40, referer: https://vmasteampasst01.nghs.com/index.php?page=items
```

**Comment by nilsteampassnet** [comment]
Is the file `teampass-seckey` generated inside your salt path?
Has the upgrade scripts ran without issue?
Can you check:
- in table `items` if values for field `pw_iv` are empty
- in table `items` if values for field `pw` start with `def`
- in table `items` if values for fied `encryption_type` equal `defuse`
Did you run several time the upgrade process? This is important to remember, this could help to find a solution. If it is the case, take a look to the backup files in salt path starting `sk.php.2017_`. Take the most recent one, open it and check if it contains a line starting with `@define('SALT', `. If no, we have the reason.

**Comment by ImNtReal** [comment]
Yes.
The scripts did not report an error.
pw_iv only has a few entries. I'm not sure why it exists for the ones it does.
All items except for ones with pw_iv have pw starting with def.
Again, it looks like those have an encryption_type of not_set. The rest are defuse.
I've only run the upgrade process once this time, but i have upgraded in this database before.
The backup sk.php file does contain a SALT, but the new one does not.

**Comment by ImNtReal** [comment]
Does the defuse encryption use a per-item salt?

**Comment by nilsteampassnet** [comment]
What I was thinking about seems correct.
I can't explain why you experiment this. Did you tried to clean your browser cache/session?
Defuse hashes the generated encryption salt with the encrypted string. That's why pw_iv is now empty( I will remove this field in the future).
No way to get connected through ammyy to evaluate with you how to help you??

**Comment by ImNtReal** [comment]
I'll try restoring a dump of the database, and rerunning the upgrade

**Comment by ImNtReal** [comment]
So, I dumped my production database, and imported it on top of my test database. Then, I cleaned out /var/lib/teampass (where my sk.php lives), and copied the one from production. I reran the upgrade, everything appeared to go well, but I got the same issue.

**Comment by ImNtReal** [comment]
Here's something:
```
[Mon Feb 27 14:17:20.890749 2017] [:error] [pid 44835] [client 172.20.69.68:59642] PHP Fatal error:  Uncaught configFileNotFoundException: OWASP CSRFProtector: configuration file not found for CSRFProtector! in /var/www/TeamPass-2.1.27.0/includes/libraries/csrfp/libs/csrf/csrfprotector.php:123\nStack trace:\n#0 /var/www/TeamPass-2.1.27.0/index.php(31): csrfProtector::init()\n#1 {main}\n  thrown in /var/www/TeamPass-2.1.27.0/includes/libraries/csrfp/libs/csrf/csrfprotector.php on line 123
```

**Comment by nilsteampassnet** [comment]
You have this php error only once in your log?
It indicates that you have no csrf config file.
Don't you have any file called csrfp.config.php in includes\libraries\csrfp\libs ?

**Comment by ImNtReal** [comment]
I do, but I did not copy it before I ran the upgrade. Does this token need to match?

**Comment by nilsteampassnet** [comment]
Logically csrfp has nothing to do with the encryption. It only protects the pages.
So for me, this has no impact on your main issue.

How many items are in your database? How many of them not have the value "defuse" in "encryption_type"?

I did a new upgrade in my testing environment, and did not encounter this case. I don't understand why some are not re-encrypted. The only case where pwd remains empty after migration where linked to a bad saltkey.

**Comment by ImNtReal** [comment]
I'll double check that the passwords are visible in the test system prior to performing an upgrade.
670 items have an encryption type of defuse, 11 do not.

**Comment by nilsteampassnet** [comment]
very strange, do you have an idea why those 11 items ... a kind fo setting, something they share together, ...

Yes please check because by reviewing the code, the only case I have identify where this happens is that the orginal saltkey is empty or wrong.

Could we have a share screen session using ammyy?

**Comment by ImNtReal** [comment]
I just verified after moving back to 26.2, and moving sk.php back to the old version, I was able to decrypt passwords. I'm not sure what those 11 items might have in common. I can try the upgrade, again, and look, again. I can share my screen with you, but I'm on EST. Would some time between 9am and 5pm EST work?

**Comment by paulojjs** [comment]
Hi,

I'm having the same problem. All my passwords are showing an "Error encrypting password!" message after upgrade 2.1.26 -> 2.1.27.

The teampass-seckey.txt appears to be ok, sk.php is empty but the previous version of the file has a SALT.

Database seems ok too:

> select count(*) from cpassman_items;
+----------+
| count(*) |
+----------+
|     6809 |
+----------+
1 row in set (0.01 sec)

> select distinct encryption_type from cpassman_items;
+-----------------+
| encryption_type |
+-----------------+
| defuse          |
+-----------------+
1 row in set (0.01 sec)

> select distinct pw_iv from cpassman_items;
+-------+
| pw_iv |
+-------+
|       |
+-------+
1 row in set (0.06 sec)

> select count(pw) from cpassman_items where pw not like 'def%';
+-----------+
| count(pw) |
+-----------+
|         0 |
+-----------+
1 row in set (0.00 sec)

No errors during upgrade process.

My server is running CentOS 7 with Apache 2.4.6 and PHP 5.5 (from SCL running as php-fpm). Database is mariadb 5.5.

**Comment by asgomes** [comment]
Hi, 
I've the exact situation of the above post from @paulojjs, and I can add the next:
I've managed to do an upgrade and noticed that the passwords were missing, despite that, we could add new passwords, and everything was right.

So the problem is with migrated passwords, in **teampass_items.pw** we had 200 characters long for older passwords(migrated) , and with the new passwords got 176 charaters long encrypted passwords.

Maybe this information can help you.

**Comment by ImNtReal** [comment]
I finally gave 2.1.27.2 a shot, but I'm still having the same issue.

**Comment by aurelti** [comment]
Hello,

I was stuck the same way but I have fixed it by :
- making sk.php immutable because the installation script delete the SALT fromthe file (chattr +1 /home/cpassman/sk.php) ;
- Apply this patch :
diff -r TeamPass/install/upgrade_run_encryption_pwd.php /var/www/pass/install/upgrade_run_encryption_pwd.php
117c117
<             $encrypt = cryption_phpCrypt($pw, SALT, "", "encrypt");
---
>             $encrypt = cryption_phpCrypt($pw, SALT, $encrypt['iv'], "encrypt");

Starting from a restored DB and launching the upgrade again made the trick for us.
Hope it helps.

**Comment by ImNtReal** [comment]
Changing permissions to deny Apache write to sk.php seems to fix the issue based on Issue #1798

**Comment by coreyramirezgomez** [comment]
I'm having a similar issue.

I upgraded from 2.1.23 to 2.1.27.7 with no errors during the upgrade.

I was able to login as an admin user with no issues.
I was able to login as an ldap user after some modifications to identify.php, which I will submit the diff for later. Unrelated to this issue.

The path to my sk.php is read-write for the apache user, but I made the sk.php read-only since #1789 affected me as well. 
Contents of the path to my sk.php:
> -r--r--r--. 1 apache apache 148 Jul  7  2014 sk.php
> -r--r--r--. 1 apache apache  29 Jul  7  2014 sk.php.2014_07_07
> -rw-r--r--  1 apache apache 148 Aug 17 10:56 sk.php.2017_08_17.1502992614
> -rw-r--r--  1 apache apache 136 Aug 17 10:56 teampass-seckey.txt

This was on a previous upgrade iteration. I restored to my snapshot and ran the upgrade again with the read-only permissions. I am now encountering this new problem. 

Most passwords are accessible, but some are not. I receive the following error when clicking on one that is inaccessible:
![screen shot 2017-08-17 at 11 17 25 am](https://user-images.githubusercontent.com/1264380/29427455-b1ce4b16-833e-11e7-91b0-7013c240cd49.png)

There's a mix of entries that are accessible and inaccessible:
![screen shot 2017-08-17 at 11 25 35 am](https://user-images.githubusercontent.com/1264380/29427669-630c07ec-833f-11e7-8119-04849f3a69e0.png)

I have restored to my snapshot of this system and attempted the upgrade by applying the modifications suggested by @aurelti. However, I received the same errors on the same entries. The counts are the same (see MySQL queries below).

For the error above, "Undefined index: session_psk", I looked at my user database entry and it seems that neither the "psk" or the "encrypted_psk" are set, which means that when main.queries.php goes to set "session_psk", there's nothing to do...

Beyond all this I am stuck...going to roll back to my 2.1.23 working version for now.

**System Info:**
**Operating system:** CentOS release 6.6 (Final)
**Web server:** Apache 2
- httpd-tools-2.2.15-60.el6.centos.5.x86_64
- httpd-2.2.15-60.el6.centos.5.x86_64

**Database:** MariaDB
- mysql-5.1.73-8.el6_8.x86_64
- mysql-server-5.1.73-8.el6_8.x86_64
- mysqltuner-1.6.0-1.el6.noarch
- mysql-libs-5.1.73-8.el6_8.x86_64
- php-mysqlnd-5.6.31-1.el6.remi.x86_64

**PHP version:** 5.6.31
- php-pecl-zip-1.15.1-1.el6.remi.5.6.x86_64
- php-tidy-5.6.31-1.el6.remi.x86_64
- php-tcpdf-dejavu-sans-fonts-6.2.13-1.el6.noarch
- php-php-gettext-1.0.12-1.el6.noarch
- php-mbstring-5.6.31-1.el6.remi.x86_64
- php-mcrypt-5.6.31-1.el6.remi.x86_64
- php-process-5.6.31-1.el6.remi.x86_64
- php-gd-5.6.31-1.el6.remi.x86_64
- php-5.6.31-1.el6.remi.x86_64
- php-pecl-jsonc-1.3.10-2.el6.remi.5.6.x86_64
- php-cli-5.6.31-1.el6.remi.x86_64
- php-bcmath-5.6.31-1.el6.remi.x86_64
- php-pdo-5.6.31-1.el6.remi.x86_64
- php-tcpdf-6.2.13-1.el6.noarch
- php-ldap-5.6.31-1.el6.remi.x86_64
- php-xml-5.6.31-1.el6.remi.x86_64
- php-mysqlnd-5.6.31-1.el6.remi.x86_64
- php-common-5.6.31-1.el6.remi.x86_64
- php-fedora-autoloader-1.0.0-1.el6.noarch
- phpMyAdmin-4.0.10.20-1.el6.noarch

**Teampass version:** 2.1.27.7

**MySQL Queries:**
> mysql> select count(pw) from teampass_items where pw not like 'def%';
> +-----------+
> | count(pw) |
> +-----------+
> |       119 |
> +-----------+
> 1 row in set (0.00 sec)
> 
> mysql> select count(pw) from teampass_items where pw like 'def%';
> +-----------+
> | count(pw) |
> +-----------+
> |       348 |
> +-----------+
> 1 row in set (0.00 sec)
> 
> mysql> select count(pw) from teampass_items;
> +-----------+
> | count(pw) |
> +-----------+
> |       467 |
> +-----------+
> 1 row in set (0.00 sec)

**Comment by polcape** [comment]
Hello, I have the same issue upgrading from 2.1.26.20 to 2.1.27.x
All password disappear, with error "Error encrypting password".

Does anyone have resolved?

Thanks

**Comment by nilsteampassnet** [comment]
You should try first migrate to the latest 2.1.26 one.

Then migrate to latest 2.1.27
