### ISSUE TITLE
Teampass 2.1.27.0 - I don't see the second sub folder in the Personal folder

### ISSUE THREAD

**Issue by userrst** [nilsteampassnet/TeamPass#1659]
We install the last version 2.1.27.0
When I create a sub folder and add an Item in the Personal folder, I don't have any problem,
but when I create a sub folder inside a sub folder I don't see the new folder after relogin.

Befor relogin:
![teampass_for_relogin](https://cloud.githubusercontent.com/assets/26093484/23416002/62cb7274-fde1-11e6-9fdf-4f336034b453.png)

After Relogin:
![teampass_after_relogin](https://cloud.githubusercontent.com/assets/26093484/23416017/723a58ec-fde1-11e6-81f9-2180b7060e11.png)

### Server configuration
**Operating system:** CentOS Linux release 7.3.1611

**Web server:** httpd.x86_64  2.4.6

**Database:** mariadb 5.5.52

**PHP version:** 5.5.38

**Teampass version:** 2.1.27.0 

**Updated from an older Teampass or fresh install:** Update from TeamPass-2.1.26-final-3

### Client configuration
**Browser: Newest Firefox and Internet Explorer**

**Operating system: Windows 10 64Bit**

#### Web server error log
```
We don't have any errors in the log File
```

**Comment by nilsteampassnet** [comment]
I confirm this.
From the 3rd level, the folder is not visible any more.

**Comment by nilsteampassnet** [comment]
OK found the issue.
In the past, it was not allowed to manage several level of sub-folders in Personal Folder.
So that when I changed this rule, I forgot to adapt the master query updating the personal folders.
So the fix is quite simple.

In file `sources/main.functions.php`, search for sentence
```
                    $ids = $tree->getDescendants($pf['id'], true, true);
```
and replace by
```
                    $ids = $tree->getDescendants($pf['id'], true, false);
```
This permits the getDescendants function to search deeper that the direct children of the User Personal Folder.
Please confirm.

**Comment by userrst** [comment]
The change had solved the problem Thanks.
