### ISSUE TITLE
Upgrading from 2.1.23 to 2.1.27.1 fails miserably

### ISSUE THREAD

**Issue by mflage** [nilsteampassnet/TeamPass#1704]
I'm trying to upgrade from 2.1.23 (skipping directly to 2.1.27 since all versions between all failed). Followed the upgrade procedure, that is backing up the database (believe me, I'm so happy I did this step), overwrote the www folder and copied the settings.php file to the new location.

Ran through /install/upgrade.php . Got a lot of questions and checks, all which were marked ok. Got to the step where the database upgrade was supposed to happen. All green thumbs. "All done".

When I then tried to log in I got the error that the can_manage_all_users column was missing. Investigated the upgrade scripts and found that this was supposed to be added from "upgrade_run_2.1.26.php" scripts, so I took the column declaration from this script and manually added it to the table: 'alter table teampass_users add can_manage_all_users tinyint(1) not null default '0';' This was successful, in the way that I was then able to actually log into Teampass. Slight improvement of the GUI it seems, but when I then tried to view a password - BLANK. NOTHING. Mask/unmasking the password shows either "******" or just "          ".

What is going on? I can see that the sk.php file has been replaced with something else? And I also see mention in the upgrade procedure that the saltkey has to be copied into a password filed (sic). Which password FIELD is this?

 

### Server configuration
**Operating system**: Debian Jessie 8.5

**Web server:** Apache 2.4.10

**Database:** 5.5.53-MariaDB-1ubuntu0.14.04.1

**PHP version:**

**Teampass version:** 2.1.27.1

**Updated from an older Teampass or fresh install:** From 2.1.23

### Client configuration
**Browser:** Different, not applicable

**Operating system:** Not applicable

#### Web server error log
```
Insert your webserver log here
```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by nilsteampassnet** [comment]
As 2.1.23 is an old version, you should try to update version by version to 2.1.25.
From 2.1.26, I have added the incremental upgrade.

2.1.27.1 is a pre-release meaning that it is not perfect. Indeed the saltkey field is not a good idea but it is now removed (in the next commit in development branch) as it was only used for files re-encryption. So it has nothing to do with the blank passwords you can experiment.

It is really strange that the upgrade couldn't add the column you are indicating and that no error was sent back. It would be interessant to get the logs from your apache server, because this must generate an error if it was not done. Even more strange is that you could then do it manually without error.

**Comment by mflage** [comment]
Hi,

well, 2.1.25 also failed (see other posts about that). Teampass started
out as a good idea, but its implementation has gone south on the latest
versions. Lots of bugs and strange behaviour in the web gui.

--
Marius

Den 22.03.2017 06.59, skrev Nils Laumaillé:
