### ISSUE TITLE
Forced Logout when opening "My Profile"

### ISSUE THREAD

**Issue by Tillco** [nilsteampassnet/TeamPass#1847]
### Steps to reproduce
1. Click on Profile Picture in upper right hand corner
2. or... Click on Extend session button and click "My Profile"
3.

### Expected behaviour
Should be able to view the my profile page. Change password, image, etc.

### Actual behaviour
A windows titled "You Personal Information" appears with nothing but an infinite turning gear and the message "Please wait!" Clicking close causes the user to be logged out to a login screen with no graphics, just plain text login fields.

### Server configuration
**Operating system**: CentOS 7

**Web server: Apache

**Database: 5.5.52-MariaDB

**PHP version: 5.6.30

**Teampass version: 2.1.27

**Teampass configuration file: 
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/1188383/tp.config.php.txt)

**Updated from an older Teampass or fresh install: Fresh Install
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser: Chrome and IE

**Operating system: Windows 10 and Windows 7

#### Web server error log
```

[access_log.txt](https://github.com/nilsteampassnet/TeamPass/files/1188389/access_log.txt)
[error_log.txt](https://github.com/nilsteampassnet/TeamPass/files/1188390/error_log.txt)
[ssl_error_log.txt](https://github.com/nilsteampassnet/TeamPass/files/1188391/ssl_error_log.txt)
[ssl_request_log.txt](https://github.com/nilsteampassnet/TeamPass/files/1188392/ssl_request_log.txt)
[ssl_access_log.txt](https://github.com/nilsteampassnet/TeamPass/files/1188393/ssl_access_log.txt)

```

#### Firebug log ([How to?](http://teampass.net/2014-02-09-how-to-communicate-an-error-log))
```
Insert the Firebug log here
```

**Comment by Tillco** [comment]
I used this for the initial setup "http://www.systeen.com/2016/12/16/install-teampass-2-1-centos-7/"

I also enable SSL, using a godaddy signed certificate.

**Comment by nilsteampassnet** [comment]
Please provide the Apache error logs.

What package did you installed?

**Comment by Tillco** [comment]
I used these instructions:
http://www.systeen.com/2016/12/16/install-teampass-2-1-centos-7/
I installed MariaDB like it explained in the link above. I had to pretty
much setup the SSL based on generic how-tos on GoDaddy's website. I can't
find anything detailed instructions on setting it up in Teampass
documentation. I provided all the HTTPD logs from the server, are the
apache logs kept somewhere else?

Thank you for any help you can offer.

Jairus

**Comment by ImNtReal** [comment]
I'm having this same issue on 2.1.27.7. This is what is in one of my recent error_logs:
`[Tue Aug 01 16:16:21.101563 2017] [:error] [pid 25110] [client 172.20.69.13:51820] PHP Notice:  Undefined index: agses_authentication_enabled in /var/www/TeamPass-2.1.27.7/sources/main.functions.php on line 1104, referer: https://vmasteampass01.nghs.com/index.php?page=manage_main
[Tue Aug 01 16:23:44.367742 2017] [:error] [pid 25949] [client 172.20.204.201:59167] PHP Notice:  Undefined index: login in /var/www/TeamPass-2.1.27.7/sources/core.php on line 185
[Wed Aug 02 09:07:31.512221 2017] [:error] [pid 25949] [client 172.20.204.43:39745] PHP Warning:  require_once(./sources/SecureHandler.php): failed to open stream: No such file or directory in /var/www/TeamPass-2.1.27.7/error.php on line 16, referer: http://teampass.nghs.com/index.php?page=items
[Wed Aug 02 09:07:31.512268 2017] [:error] [pid 25949] [client 172.20.204.43:39745] PHP Fatal error:  require_once(): Failed opening required './sources/SecureHandler.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/TeamPass-2.1.27.7/error.php on line 16, referer: http://teampass.nghs.com/index.php?page=items`
This is the infinite cog screen:
![teampass_profile](https://user-images.githubusercontent.com/2048112/28875590-a6c7ac4c-775b-11e7-89b4-cbb6cc61cdca.png)
And here is what happens if I click cancel:
![teampass_not_allowed](https://user-images.githubusercontent.com/2048112/28875600-b32b7310-775b-11e7-9031-43638fdc0f3d.png)
I've even tried deleting my account, and recreating it. I was still able to reproduce the issue. It happens with my local admin account, or LDAP accounts.

**Comment by ImNtReal** [comment]
If this issue is closed as a duplicate, is there a different issue I should be posting this on? thanks.

**Comment by Tillco** [comment]
I was told this is an error with my SSL, I confirmed that when I disabled SSL and used HTTP, it all seems to work correctly. Anyone have details on exactly how we should setup the SSL for TeamPass?

**Comment by ImNtReal** [comment]
I'm able to reproduce my issue using http.

**Comment by ImNtReal** [comment]
Interesting. If I remove all references to https from my configuration, and then use http, my profile works, but if I reference https URLs in the config it breaks whether or not I use https to access the site.

**Comment by Tillco** [comment]
Hoping someone has figured out the answer to this. We still can't use several parts of TeamPass when we use SSL.
