### ISSUE TITLE
Installation of current master fails

### ISSUE THREAD

**Issue by Sailing74** [nilsteampassnet/TeamPass#1863]
### Steps to reproduce
Install from scratch. Installation fails at step "finalization" with three green checkmarks and the message "At least one task has failed! Please correct and relaunch."
There is no hint as to which step has actually failed and what the issue is.

**Operating system**: Ubuntu 16.04.3

**Web server:** Apache/2.4.18 (Ubuntu)

**Database:** mysql  Ver 14.14 Distrib 5.7.19

**PHP version:**  v7.0.18-0ubuntu0.16.04.1

**Teampass version:** github-master

**Teampass configuration file:** n.a., new installation

**Updated from an older Teampass or fresh install:**
fresh install

### Client configuration
**Browser:** Firefox

**Operating system:** Windows

#### Web server error log
empty
last line from access.log
```
192.168.1.3 - - [11/Aug/2017:12:50:07 +0200] "POST /teampass/install/install.queries.php HTTP/1.1" 200 576 "https://www.domain.com/teampass/install/install.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
```

![error](https://user-images.githubusercontent.com/5119859/29210498-2c966fcc-7e94-11e7-9b75-1c0bc73a662f.jpg)

**Comment by B0T0B** [comment]
Hello!
Did you restart the wizzard installation at some point?
I was able to reproduce the message. By looking at the network traffic, I can see that : 

> csrfp.config.php file already exists and cannot be renamed. Please do it by yourself and click on button Launch.

What you can do is to (re)move the file /your/teampass/path/includes/libraries/csrfp/libs/csrfp.config.php and clic on Launch and the problem should be gone.

After that, you may not be able to log because the install directory is not removed correctly. So when you are at the login screen, remove the /your/teampass/path/install/ directory and there you are :)

**Comment by Sailing74** [comment]
Indeed, with these additional steps it works. Thanks!
