### ISSUE TITLE
How to recover my password after I lost my salt key

### ISSUE THREAD

**Issue by Carolhug** [nilsteampassnet/TeamPass#1938]
### Steps to reproduce
1. mysqldump database from old Teampass
2. import the database to new Teampass
3. Password is becoming to blank in new Teampass

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system Docker Kubernetes **: 

**Database: mysql 5.7 **  

**Teampass version: 2.1.26**  

**Teampass configuration file: docker file ** 

**Updated from an older Teampass or fresh install: Fresh install but import the data from older Temapss, we wipped the old Teampass before we realize to decrypt the password needs the old salt key. **

PLEASE attach to this message the file `/includes/config/tp.config.php
[tp.config.docx](https://github.com/nilsteampassnet/TeamPass/files/1340154/tp.config.docx)`

### Client configuration
**Browser:** Chrome and Firefox 

**Operating system:**
Centos 7.3 
#### Web server error log
```
no log ```#### Log from the web-browser developer console (CTRL + SHIFT + i)

**Comment by nilsteampassnet** [comment]
If you have not the saltkey, the encrypted data in the database is forever lost. 
The saltkey is a key. Without the key, you cannot open the door.

Now if you try to use a dump created with an old version of teampass, you must use the Teampass files corresponding. You cannot restore an old database because the structure may have changed.
So you need to go through the upgrade processes to reach the matching structure of the DB to the instance of your teampass files.

**Comment by nilsteampassnet** [comment]
If during installation process no specific path is set for this file, then it is created inside /includes/ folder.

I hope it was not changed for you even if it is a bad practice in term of security.

**Comment by Carolhug** [comment]
LOL, it's not there.


Oh, no, I have to spend a lot of time to find back all the password that recorded in the old teampass system.


But anyway, thanks for your help here, really appreciated.


Thanks.

- Carol

________________________________
