### ISSUE TITLE
Warning appears on Category and API pages in admin mode

### ISSUE THREAD

**Issue by jcoquery** [nilsteampassnet/TeamPass#1956]
### Steps to reproduce
1. Log into admin
2. Go to Parameters.
3. Click on Category or API

### Expected behaviour
no Warning

### Actual behaviour
2 warning appears

### Server configuration
**Operating system:** Docker (Centos)

**Web server:** Apache

**Database:** 5.7.19

**PHP version:** 7.1.9

**Teampass version:** 2.1.27

**Teampass configuration file:**
[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/1359603/tp.config.txt)

### Client configuration

**Browser:** All

**Operating system:** Windows 10

![tp error-cat](https://user-images.githubusercontent.com/30726879/31231721-f76055dc-a9e7-11e7-9387-dde08ca6d2bf.png)
![tp error-api](https://user-images.githubusercontent.com/30726879/31231725-fa1336f0-a9e7-11e7-92c2-cb4e27cc37a3.png)

**Comment by nilsteampassnet** [comment]
Sorry I couldn't reproduce too.
Can you please give me the exact version you use?
![image](https://user-images.githubusercontent.com/1197546/31240031-735ccffa-a9ff-11e7-8eaf-524bf2f38dec.png)

Can you check is?

<quote>
Do the following value match the url you enter to access the application :
jsUrl, found in includes/libraries/csrfp/libs/csrfp.config.php. If the value is "https://my.beautiful.password.manager/includes/libraries/csrfp/js/csrfprotector.js, the url which you use to access the web application should be https://my.beautiful.password.manager/index.php. Otherwise, a "Hacking attempt..." will be sent through a POST response by the server and your session will be terminated.
<quote>

**Comment by jcoquery** [comment]
The version is the same as you 2.1.27.9. But run with a docker-compose file.
I don't understand what I must look at in the csrfp config, but the line is:
 "jsUrl" => "https://teampass.monsite.int/includes/libraries/csrfp/js/csrfprotector.js",

Thanks

**Comment by nilsteampassnet** [comment]
Can you please try the next thing?

* Edit file `admin.settings_categories.php`,
* move the 2 lines
`require_once('sources/SecureHandler.php');
session_start();`
* before the `?>` that is just after the file warning usage

Once done, you should have something that looks like this
`
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

require_once('sources/SecureHandler.php');
session_start();
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html><head><title>API Settings</title></head><body>

<?php
if (!isset($_SESSION['CPM']) || $_SESSION['CPM'] != 1) {
    die('Hacking attempt...');
}
`

**Comment by jcoquery** [comment]
Hi,
It was almost that.
With this modification, the warning still appear because of the line `header("Content-type: text/html; charset=utf-8");`
So, to resolve this issue, you must move the 2 lines:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html><head><title>API Settings</title></head><body>
```
just after the first "echo" arround line 102.
In the file admin.settings_api.php the solution is the same.
Move the fist html part (between the line 20 and 60) just after the first echo (line 107).

Thanks

**Comment by nilsteampassnet** [comment]
Thank you for the feedback
