### ISSUE TITLE
Duo 2 factor authentication process doesn't work with admin credentials

### ISSUE THREAD

**Issue by josesalazar051989** [nilsteampassnet/TeamPass#1998]
### Steps to reproduce
1. Enable Duo Login 2 factor login tool
2. Try to login with admin credentials. 

Is important to clarify that this doesn't happen with the other users, just with the admin user.

### Expected behaviour
Duo Login interface must appear and request for the 2 factor login process (call, push notification, etc)

### Actual behaviour
I login immediately without the 2 factor verification process

### Server configuration
Linux Debian

Apache 2.x

MySql 5.5

PHP 5.6

**Teampass version:** 

Teampass 2.1.27

### Client configuration
Google Chrome

Linux Debian

**Comment by nilsteampassnet** [comment]
It is by design.

Admin account is excluded from this.

**Comment by josesalazar051989** [comment]
@nilsteampassnet thanks for your quick response. It's clear for me now, so if i want to increase the administrator account security, which is the option?

Regards.

**Comment by nilsteampassnet** [comment]
Today you need to change its login and define a very heavy password.

The problem is that if we add duo or whatever 2factor mechanism also to 'admin' accounts, and that you have indicated bad information then the admin will not be able to enter in Teampass to perform the fix.

So my only advice is to do as written in my 1st sentence.
