### ISSUE TITLE
Deactivated AD users can still login in Teampass

### ISSUE THREAD

**Issue by mr-gosh** [nilsteampassnet/TeamPass#2281]
deactivated Active Directory Users can still login to Teampass

### Steps to reproduce
1. create ad user
2. login to teampass
3. deactivate user in AD
4. login in teampass still possible

### Expected behaviour
the user should not be able to login to teampass if account is disabled

### Actual behaviour
the user is still able to login via his (now deactivated) credentials
### Server configuration
**Operating system**:
Ubuntu 16.04 LTS with docker

**Web server:**
nginx

**Database:**
mariadb

**PHP version:**
7.1

**Teampass version:** 
2.1.27

**Comment by nilsteampassnet** [comment]
Yes you are right.

This should be added

**Comment by mr-gosh** [comment]
Even the change of a password is not recognized on the fly.

**Comment by nilsteampassnet** [comment]
No for sure as if a user is logged in then his session is valid until expiration or log out.

**Comment by phandox** [comment]
Hello, do we have any ETA on this feature? I believe it's critical feature.

**Comment by mr-gosh** [comment]
@nilsteampassnet its not only the current session, if i add a ad user with password xyz
than he can login with "xyz" - if the user password is changed, he can still login with "xyz" and if the user is deactivated in AD than he still can login with "xyz" as if the user is copied once to teampass... :-1:

**Comment by nwildner** [comment]
Hi @nilsteampassnet . I can confirm this issue. I've created a test user and we have the following AD/LDAP setup here(i'll supress any sensitive information from my company):

- Windows / Active Directory
- **Suffix:** `@domain.net`
- **BASE DN:** `dc=domain,dc=net`
- **Allowed LDAP Group:** `G-USERS-TEAMPASS`
- **DC Controllers:** `dc01.domain.net, dc02.domain.net`
- **LDAP port:** `389`

Windows Server 2012 R2 as Domain Controller.

**Steps to reproduce:**

- Create an AD user.
- Add membership to LDAP Group `G-USERS-TEAMPASS`.
- Log in first time on Teampass.
- Disable User inside "Active Directory Users and Computers".
- User will be able to login even with a domain disabled account.

As a System Administrator myself, I find this behavior to be a bug not a "feature" since this can impact greatly on the way we handle user access revocation.

**Comment by nilsteampassnet** [comment]
Yes @nwildner You are right.
I will work on fixing it

**Comment by nilsteampassnet** [comment]
While looking the code.
I have added this check already on "posix-search".
But it is missing in other type of ldap.

My test environment doesn't include other type of ldap than posix-search.
So I will require your help.

Can you please do the next change and provide me the results?

* Open in edit mode the file `sources/identify.php`
* Search for (around line 840)
```
                // Update user's password
                if ($ldapConnection === true) {
                    $data['pw'] = $pwdlib->createPasswordHash($passwordClear);
```
* Replace by 
```
                // Is user disabled?
                $user_info_from_ad = $adldap->user()->info($auth_username, array("useraccountcontrol"));
                if ((($user_info[0]['useraccountcontrol'][0] & 2) == 0) === false) {
                    echo '[{"value" : "user_disabled'.$auth_username.'", "text":""}]';
                    exit();
                }

                // Update user's password
                if ($ldapConnection === true) {
                    $data['pw'] = $pwdlib->createPasswordHash($passwordClear);
```

Thank you
