### ISSUE TITLE
Trouble adding new users.

### ISSUE THREAD

**Issue by LibreBeats** [nilsteampassnet/TeamPass#2380]
Hello there,

A company I recently started working for uses TeamPass (and everyone here is quite happy doing so, I have to add, great software!), and when adding me and some other new employees we have found the following two issues:

a) They outright can't add new users: Apparently, after upgrading to a new version at some point in the past, the "psk" field was changed to "encrypted_psk", and it complained that the field "psk" should not be empty. We tried replacing "encryted_psk" to "psk" in sources/user.queries.php, it then complained that it needed the other field as well, added both, problem apparently solved.

b) Now that users could be added, we found out that they could not be given access to all of the shared folders. Testing things out, the limit was between 63-65, depending on the folders chosen. So, back to the database! We manage 700+ folders, so, fiddling out a bit, with the autoincrement and all, we  are nearing 4 digit ids, plus the semicolon added to differentiate entries in "groupes_visibles", it gets to 2-5 chars per folder. "groupes_visibles" is defined as a varchar(250), changing that to varchar(10000) fixes the problem (for now, we know once we get to the 4 digit ids the limit may have to be higher).

As you can see, the problems themselves are sorted out, but we are wondering if there could be any unforeseen side-effect and what are your thoughts on that. I wish I could be more clear regarding the steps to reproduce and following the exact template, but it has been a year or more since the last time a user was added and these problems had not appeared before, so we do not really know when those things might have changed, or if any update-script has been missed or something of the sort.

Thanks for your time and, again, for Teampass! Great password manager, man!

**Comment by nilsteampassnet** [comment]
Thank you.

Regarding a), can you tell me from what release to what release you upgraded?
You are absolutely right, Teampass requires both fields `psk` and `encrypted_psk` to work correctly.

Regarding b), I'm impressed that you have set so much allowed folders to each of your users that you have a string longer then 255 characters. But indeed if it is the case, you have done it right to increase this value directly inside the database. I could do this change inside Teampass too.
Now I'm wondering if you are using the correct "method" to set your users access to Folders.
I would like you to check if you can change this by working more with Roles.
Indeed it is more efficient to work with Roles rather than with "Allowed folders" field.
Define several Roles, set the access rights to the Folders, then allocate the Role to the User.

Is this something you also did?

**Comment by LibreBeats** [comment]
Hello again!

I'll answer b) first, because indeed it works better with roles! We were using roles indeed, but also adding the folders to each of us who needed access to them. Now it works perfectly! We had figured those two were independent things. I took a look again at the db to check the roles tables and didn't see any folder id, so I'm guessing it's in the nested folders table where the role ids are saved right?

Regarding a) we upgraded 2.1.26 to 2.1.27.5 last November, and 2.1.26.5 to 2.1.27.16 last week. Unfortunately, though, as I already mentioned, we don't really have a way of knowing when exactly did we start experiencing this issues, since we do not add a user that often!

Thanks again for your quick and helpful reply!!
