### ISSUE TITLE
TeamPass always needs mcrypt !

### ISSUE THREAD

**Issue by FlorentCoppint** [nilsteampassnet/TeamPass#2446]
Hi,

I'm using TeamPass 2.1.27.23 and it can't run on PHP 7.2 because it always uses mcrypt functions !

Users can't login : 

> [Mon Oct 22 14:51:56.353049 2018] [php7:error] [pid 5091] [client 10.111.111.132:57392] PHP Fatal error:  Uncaught Error: Call to undefined function mcrypt_create_iv() in /var/www/teampass/sources/main.functions.php:196\nStack trace:\n#0 /var/www/teampass/sources/identify.php(1223): encrypt('57641f5e2af93cf...', '')\n#1 /var/www/teampass/sources/identify.php(313): identifyUser('WgARH+zHzVs2Xto...', 0, 0, Array)\n#2 {main}\n  thrown in /var/www/teampass/sources/main.functions.php on line 196

I thought TeamPass was not using mcrypt anymore ?!

**Comment by nilsteampassnet** [comment]
mcrypt is not used any more on "normal" commands.
But it is still used if the user has not been connected since the migration and that still using the old encryption system.
This means that you have an option "Use login password as personal salt key (easier, less secure)" enabled.
I could also invest some time to improve this.
