### ISSUE TITLE
JSON Error while Searching Items

### ISSUE THREAD

**Issue by samuelokoh** [nilsteampassnet/TeamPass#2464]
### Steps to reproduce
1. If I click on search button, i get a JSON error 

### Expected behaviour
Items supposed to show when I click on search button

### Actual behaviour
If I click on search button, i get a JSON error 

### Server configuration
**Operating system**:
Debian Strecht

**Web server:**
NGINX

**Database:**
MySQL

**PHP version:**
7

**Teampass version:** 
2.1.27.24

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome, Explorer, Firefox

**Operating system:**
Windows 10, Windows 7

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
https://xxxxx/sources/find.queries.php?sEcho=1&iColumns=7&sColumns=,,,,,,&iDisplayStart=0&iDisplayLength=10&mDataProp_0=0&sSearch_0=&bRegex_0=false&bSearchable_0=true&bSortable_0=true&mDataProp_1=1&sSearch_1=&bRegex_1=false&bSearchable_1=true&bSortable_1=true&mDataProp_2=2&sSearch_2=&bRegex_2=false&bSearchable_2=true&bSortable_2=true&mDataProp_3=3&sSearch_3=&bRegex_3=false&bSearchable_3=true&bSortable_3=true&mDataProp_4=4&sSearch_4=&bRegex_4=false&bSearchable_4=true&bSortable_4=true&mDataProp_5=5&sSearch_5=&bRegex_5=false&bSearchable_5=true&bSortable_5=true&mDataProp_6=6&sSearch_6=&bRegex_6=false&bSearchable_6=true&bSortable_6=true&sSearch=&bRegex=false&iSortCol_0=1&sSortDir_0=asc&iSortingCols=1&_=1541430337485
![jason_error](https://user-images.githubusercontent.com/44702574/48006969-de4e3e80-e116-11e8-8ec1-e84cbc8d671d.PNG)

Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
I cannot reproduce.

Can you please reproduce and get the error from the web console following [instructions](https://teampass.readthedocs.io/en/latest/faq/#how-to-capture-query-error-from-the-browser-console)

**Comment by EricLF** [comment]
Same error here !

Steps to reproduce

    If I click on search button, i get a JSON error:
DataTables warning: table id=t_items - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

Expected behaviour

Items supposed to show when I click on search button
Actual behaviour

If I click on search button, i get a JSON error:
DataTables warning: table id=t_items - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

Server configuration

Operating system:
Debian Strecht

Web server:
Apache

Database:
MySQL

PHP version:
7

Teampass version:
2.1.27

Teampass configuration file:

Updated from an older Teampass or fresh install:
fresh install

PLEASE attach to this issue the file /includes/config/tp.config.php.
Client configuration

Browser:
Chrome, Explorer, Firefox

Operating system:
Windows 10, Windows 7
Logs
Web server error log
