### ISSUE TITLE
Password cannot be modified and directory unseen in folder management

### ISSUE THREAD

**Issue by iTKFred** [nilsteampassnet/TeamPass#2473]
### Steps to reproduce
1. Select directory "Env - ITK", Add item
2. Label test, Login test, Generate password, Save
3. Message "You must enter your personal salt key!" appears
4. Set salt key and save (my salt key is registered in my browser)
5. Reproduce step 1 & 2

### Expected behaviour
Password created, possibility to modify it, no salt key message

### Actual behaviour
The test item created cannot be modified but can be deleted and has an orange flag on the left.
This behaviour doesn't happen on other directories. When I log in the admin interface, I don't see "Env - ITK" in the Folder Management or in the Role Management.

### Server configuration
**Operating system:** Debian 8

**Web server:** Apache 2.4.10-10+deb8u12

**Database:** MySQL 5.5.62-0+deb8u1

**PHP version:** 5.6.38+dfsg-0+deb8u1

**Teampass version:** 2.1.27.21 (also tested in 2.1.29)

**Teampass config file:** [tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/2572555/tp.config.php.txt)

**Updated from an older Teampass or fresh install:** Upgraded from Teampass 2.1.26
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Firefox 63 

**Operating system:** Ubuntu 18.10

**Comment by nilsteampassnet** [comment]
I'm not sure to understood everything.

Regarding the 1st point, I don't have any issues to modify a personal item.
the described steps to reproduce seems strange.
Indeed if you have not set your saltkey, when you click "Add an item" inside a personal folder, then no create dialogbox is shown but instead a warning asking you to set your saltkey.
perhaps is there some misunderstanding here.
Can you please detail all steps with screenshots so that I can understand better what actions you are performing?

Regarding 2d, it is normal that such folder is not visible in admin folders, because they are personal.
So an admin cannot access them.
Keep in mind that personal folders/items are private to the user. They cannot be shared or viewed by anyone else.

**Comment by iTKFred** [comment]
Hello, 

I'll try and explain with screenshots, it should be easier :) 

The problem is the "test" password in this screenshot 

If I do the exact same steps in the "Env - Azure" folder, I don't have any problem. The folder "Env - ITK" is not supposed to be a personal folder, it is shared among users and has worked perfectly before. 

When I log in as an admin and go to the "Manage Folders" screen, I don't see the "Env - ITK" folder but I see the "Env - Azure" folder, which makes me think that something's wrong. 


It looks like Teampass is considering "Env - ITK" as a personal folder but I don't understand why and don't know how to change this. 

Any idea ? 

Thanks 



-- 


	

Frédéric MARTINOTY 

Responsable SI 

+33 (0)6 08 34 19 53 

@ [ mailto:frederic.martinoty@itk.fr | frederic.martinoty@itk.fr ] 
	

ITK 

Cap Alpha 
Avenue de l'Europe 
34830 Clapiers 

[ http://itk.fr/ | www.itk.fr ] 
Enregistrer Enregistrer 


De: "Nils Laumaillé" <notifications@github.com> 
À: "nilsteampassnet/TeamPass" <TeamPass@noreply.github.com> 
Cc: "Frédéric MARTINOTY" <frederic.martinoty@itk.fr>, "Author" <author@noreply.github.com> 
Envoyé: Lundi 12 Novembre 2018 20:03:46 
Objet: Re: [nilsteampassnet/TeamPass] Password cannot be modified and directory unseen in folder management (#2473) 



I'm not sure to understood everything. 

Regarding the 1st point, I don't have any issues to modify a personal item. 
the described steps to reproduce seems strange. 
Indeed if you have not set your saltkey, when you click "Add an item" inside a personal folder, then no create dialogbox is shown but instead a warning asking you to set your saltkey. 
perhaps is there some misunderstanding here. 
Can you please detail all steps with screenshots so that I can understand better what actions you are performing? 

Regarding 2d, it is normal that such folder is not visible in admin folders, because they are personal. 
So an admin cannot access them. 
Keep in mind that personal folders/items are private to the user. They cannot be shared or viewed by anyone else.

**Comment by iTKFred** [comment]
Comment edited, looks like my screenshots weren't available when I answered by email. It should be better, now

**Comment by nilsteampassnet** [comment]
How strange.
I just see one possibility.
Someone has moved it inside his personal folder.
And when saw the mistake, he copied it back.
Perhaps the issue comes from such manipulation.

Can you please run the query : 
```SELECT personal_folder, id FROM `teampass_nested_tree` WHERE `title` LIKE '%Env - ITK%' ```

If it returns the first value with `1` then it is a personal folder for Teampass. The second number is the folder `ID`

You can roll it back to normal folder using the next query:
````
UPDATE `teampass_nested_tree` SET `personal_folder` = '1' WHERE `teampass_nested_tree`.`id` = <ID>;
```
Replace `<ID>` with the `ID` from previous query?

Before this, one question, can you access normally to the items inside this folder?

**Comment by iTKFred** [comment]
It worked :)

The folder "Env - ITK" was seen as a personal folder whereas "Env - Azure" wasn't : 

mysql> SELECT personal_folder, id FROM `teampass_nested_tree` WHERE `title` LIKE '%Env - ITK%';
+-----------------+-----+
| personal_folder | id  |
+-----------------+-----+
|               1 | 282 |
+-----------------+-----+
1 row in set (0.01 sec)

mysql> SELECT personal_folder, id FROM `teampass_nested_tree` WHERE `title` LIKE '%Env - Azure%';
+-----------------+-----+
| personal_folder | id  |
+-----------------+-----+
|               0 | 327 |
+-----------------+-----+
1 row in set (0.01 sec)

I updated it and now both folders behave in the same way

mysql> UPDATE `teampass_nested_tree` SET `personal_folder` = '0' WHERE `teampass_nested_tree`.`id` = 282;
Query OK, 1 row affected (0.02 sec)
Rows matched: 1  Changed: 1  Warnings: 0

Thanks :)
