### ISSUE TITLE
SyntaxError: Unexpected end of JSON input, on some folder after upgrade to 2.1.27.33

### ISSUE THREAD

**Issue by baudettespiria** [nilsteampassnet/TeamPass#2523]
### Steps to reproduce
1. upgrade from 2.1.26-final-3 to 2.1.27.33
2. click on folder items

### Expected behaviour
see the items in the folder.  On some folder its working and I see the item with the password decrypted.

### Actual behaviour
SyntaxError: Unexpected end of JSON input

### Server configuration
**Operating system**: debian 8

**Web server:** apache 2.4

**Database:** mysql 5.5

**PHP version:** 5.6

**Teampass version:** 2.1.27.33

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/2770870/tp.config.php.txt)

PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
chrome
**Operating system:**
win10
#### Web server error log
no error

#### Log from the web-browser developer console (CTRL + SHIFT + i)

jquery.js:631 Uncaught TypeError: Cannot read property 'length' of undefined
    at Function.each (jquery.js:631)
    at showItemsList (index.php?page=items:2536)
    at Object.success (index.php?page=items:2501)
    at fire (jquery.js:3048)
    at Object.fireWith [as resolveWith] (jquery.js:3160)
    at done (jquery.js:8235)
    at XMLHttpRequest.callback (jquery.js:8778)

Insert the log here and especially the answer of the query that failed.
answer from items.query.php ( if i check the folder who works, I can see a longer answer from them )

FAZBXAoKCgo=

**Comment by MrDiabolik85** [comment]
Hi,
I have the same problem.
My configuration:

Database: 10.3.12-MariaDB MariaDB Server
OS: CentOS release 6.10 
PHP versione:  5.6.39 
Teampass version: 2.1.27

Browser:
chrome and firefox
Operating system:
win10 and ubuntu

Someone has solved?

Thanks

**Comment by baudettespiria** [comment]
> Hi,
> I have the same problem.
> My configuration:
> 
> Database: 10.3.12-MariaDB MariaDB Server
> OS: CentOS release 6.10
> PHP versione: 5.6.39
> Teampass version: 2.1.27
> 
> Browser:
> chrome and firefox
> Operating system:
> win10 and ubuntu
> 
> Someone has solved?
> 
> Thanks

Do you have some folder working and others not like me too ?

**Comment by baudettespiria** [comment]
Its normal passwd with no special character in the name or what ever.

**Comment by MrDiabolik85** [comment]
hi, 
all folder no working.
Yes, special character in passwd.

**Comment by niallfleming** [comment]
I've got the same issue, only I think it's all folders for me. I suspect something missing from upgrade process. Updated from 2.1.23.x via the recommended path on readthedocs.

Ran into an issue with LIMIT which I resolved by switching max for auto on max items retrieved per query. Now I just get no errors on server side and empty JSON objects on the web browser, and a jQuery length exception, which i presume is because the object is empty.

**Comment by ekpat** [comment]
I‘ve got the same issue after updating to 2.1.27.34. The error occurs only on existing folders. The problem didn’t occur with a newly created folder and item.
Currently I’m on 2.1.26 and having another problem. 42 out of 3800 from our passwords contain “&#92;”. That string is being converted into a backslash automatically which makes those passwords useless. I wanted to update to 2.1.27.34 in order to get that issue resolved, but as described before the update breaks the application.

Running on CentOS 7, mysql and php56w.

**Comment by exeral** [comment]
same for me on all folders
upgrading from 2.1.26-final3 TO 21.27.32 or 2.1.27.36

**Comment by filinovs** [comment]
same for me on all folders
after upgrading from 2.1.26-final3 TO 2.1.27.36

SyntaxError: Unexpected end of JSON input

jquery.js:631 Uncaught TypeError: Cannot read property 'length' of undefined
    at Function.each (jquery.js:631)
    at showItemsList (index.php?page=items:2541)
    at Object.success (index.php?page=items:2506)
    at fire (jquery.js:3048)
    at Object.fireWith [as resolveWith] (jquery.js:3160)
    at done (jquery.js:8235)
    at XMLHttpRequest.callback (jquery.js:8778)
