### ISSUE TITLE
debugLdap enabled by default

### ISSUE THREAD

**Issue by dset0x** [nilsteampassnet/TeamPass#2713]
Hello,

It seems debugLdap is enabled by default. This is a security concern from what I can tell.

### Steps to reproduce
1. Use "Test current configuration" in LDAP settings

### Expected behaviour
Test password should not be stored in plaintext and word-readable by default

### Actual behaviour
https://github.com/nilsteampassnet/TeamPass/commit/ea9838481a58879cdf3def31046955efcff5a546#diff-61809be6a8fff101e3748a0c7dfad90bR16

### Server configuration
Docker-compose as per instructions

**Updated from an older Teampass or fresh install:** No

**Comment by ozawa-hi** [comment]
I've also seen several problems with docker-compose and decided to install it manually.

**Comment by dset0x** [comment]
@ozawa-hi This is not a problem with docker-compose, but a bug in the code (as linked above)

**Comment by bstapes** [comment]
By default, the debug file (`ldap.debug.txt`) is accessible without authentication.
`curl http://<your teampass instance>/teampass/files/ldap.debug.txt`

Part of the fix should include:
- Ensure that existing ldap.debug.txt files are removed. This will protect users who update and may have exposed sensitive information due to this bug.
- Notify users to change their LDAP passwords
