### ISSUE TITLE
Can't import password

### ISSUE THREAD

**Issue by EdoardoMDP** [nilsteampassnet/TeamPass#2759]
Hi all,

I need to export data from teampass (2.1.27.32) to another one(2.1.27.36).
By exporting the database I can import everything except the passwords.
I tried to export the folders to CSV but when I import the CSV I get error 500.
Someone can help me?
thanks

**Comment by MaydayZA** [comment]
I am also having an Error 500 message appear when uploading to Teampass since we have upgraded our Teampass to version 2.1.27.36. I cannot upload CSV or KeePass files anymore since the upgrade.

I have not found a solution yet either. The new version did fix other issues but introduced this error 500 as a new issue.
