### ISSUE TITLE
New server migrate database and no passwords show, moved the required files.

### ISSUE THREAD

**Issue by dragonsage00** [nilsteampassnet/TeamPass#2905]
### Steps to reproduce
1. Install new server TeamPass 2.1.27.36
2. Export database from old server TeamPass 2.1.27.33
3. Copy over sk.php and secret ket.txt
4. Server fails to start.
5.  Reset sk.php and secret.key server loads no passwords.

### Expected behaviour
Server should load with passwords
### Actual behaviour
Server does not load after coping files
### Server configuration
Debian 10
**Web server:**
Apache2
**Database:**
MariaDB
**PHP version:**
7.1
**Teampass version:** 
2.1.27.36
**Teampass configuration file:**
Old server:
<?php
global $lang, $txt, $pathTeampas, $urlTeampass, $pwComplexity, $mngPages;
global $server, $user, $pass, $database, $pre, $db, $port, $encoding;

### DATABASE connexion parameters ###
$server = "localhost";
$user = "teampass";
$pass = "def50200f7f73f170d86de8a67e56652b5bc44dc1365f386137ec631094048d6a7e5106651380cd20dc7d25059c83449fe98107f04a147c5dad7945d425fdacaa3704778579b515c0bda42ceb3b01ebb835dd454b3ca0bd3b1a7a19366";
$database = "teampass";
$pre = "teampass_";
$port = 3306;
$encoding = "";
@date_default_timezone_set($_SESSION['settings']['timezone']);
@define('SECUREPATH', 'C:/wamp64/www/teampass/includes');
if (file_exists("C:/wamp64/www/teampass/includes/sk.php")) {
    require_once "C:/wamp64/www/teampass/includes/sk.php";
}
New Server:

<?php
global $lang, $txt, $pathTeampas, $urlTeampass, $pwComplexity, $mngPages;
global $server, $user, $pass, $database, $pre, $db, $port, $encoding;

### DATABASE connexion parameters ###
$server = "127.0.0.1";
$user = "teampass";
$pass = "def5020017c02804b890ce616f4e9745597276060e7800ea248b3ee52c99284d6666ed$
$database = "teampass";
$pre = "teampass_";
$port = 3306;
$encoding = "";

@date_default_timezone_set($_SESSION['settings']['timezone']);
@define('SECUREPATH', '/var/www/html/teampass/includes');
if (file_exists("/var/www/html/teampass/includes/sk.php")) {
    require_once "/var/www/html/teampass/includes/sk.php";
}

**Updated from an older Teampass or fresh install:**
Fresh Install
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 10
#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by paulojrsti6** [comment]
I am also having the same error, I was unable to find a solution or document that shows step by step for backup and restore to new server

**Comment by dragonsage00** [comment]
> I am also having the same error, I was unable to find a solution or document that shows step by step for backup and restore to new server

you find a solution?

**Comment by paulojrsti6** [comment]
> > I am also having the same error, I was unable to find a solution or document that shows step by step for backup and restore to new server
> 
> you find a solution?

Hello, I managed to solve this problem yesterday, what I did was the following: I backed up the database in two ways to test, a mysqldump via the command line, and another backup of the database made by the teampass. I also backed up the entire folder to another location to restore later. On the new server I installed the teampass again, until I reach the login screen, I logged in with the admin user and did nothing else. Right after that I renamed the folder inside / var / www / html / teampass to _teampassold and placed the complete folder that had been backed up, replacing the entire folder.

After several unsuccessful attempts just by saving the secret key file, and restoring it, my passwords were blank, after replacing and saving the entire folder, the passwords appeared on the new server, in short, backup of the bank, and backup of the complete folder of the old to the new server. Sorry for the typos because I speak from Brazil and I used a translator.

**Comment by dragonsage00** [comment]
Thank you!  No troubles, I worked with a dev team out of Brazil in one of past jobs. Cool people, like you!

I'll give it a go and see what happens.

**Comment by paulojrsti6** [comment]
> Thank you! No troubles, I worked with a dev team out of Brazil in one of past jobs. Cool people, like you!
> 
> I'll give it a go and see what happens.

Very good, as soon as the test comes back to me to see if it worked, I researched it for about 30 days, then I decided to copy the entire folder and replace it on the new server and it worked. I didn't find anything to restore correctly in the documentation
