### ISSUE TITLE
Teampass 3 - password display

### ISSUE THREAD

**Issue by michaldejmek** [nilsteampassnet/TeamPass#3002]
Hello, 

would it be possible to make it behave the same as version 2? Now when I select a folder from the tree and then want to view the password, I have to open the item. It doesn't seem very logical to me. It was handled better in version 2. There is an unnecessary step for me.

Thank you.

**Comment by nilsteampassnet** [comment]
You need to enable quick icons
![image](https://user-images.githubusercontent.com/1197546/149616027-64dfc06d-0748-4968-b139-71ba0e3f0264.png)
So that users have access to icons permitting to copy without open
![image](https://user-images.githubusercontent.com/1197546/149616048-4307ca08-89ba-4461-93d8-85afac8ebb03.png)

**Comment by michaldejmek** [comment]
When you click on the icon nothing happens :( Only an error image pops up that says nothing . 

![image](https://user-images.githubusercontent.com/18729181/149617187-fc083931-513f-4273-b195-f162cf2a5d6f.png)

**Comment by michaldejmek** [comment]
Icons have the same problems:

- Offline mode HTML export enabled
- Show more counters in folder tree
- Enable copy password icon on item list
- Allow user to perform massive move and delete operations

**Comment by nilsteampassnet** [comment]
Please provide the log from the browser console when such dialog occurs.
How to? please read https://teampass.readthedocs.io/en/latest/faq/
