### ISSUE TITLE
Database updates 3.0.0.9 Row size too large

### ISSUE THREAD

**Issue by geokh** [nilsteampassnet/TeamPass#3005]
Dear support,

Iam facing the below issue when reaching the database upgrade:
from version Upgrading from 2.1.27.36 to 3.0.0.9 
i tried Error upgrading to Teampass 3.0 #2866 but no fixed.

An error occurred. Please check and relaunch.
09:24:54 - ERROR: An error appears when adding field public_key to table USERS! Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs!
09:24:54 - upgrade_run_3.0.0.php - Loop #1 

Regards

**Comment by basfeo** [comment]
hello. I am currently upgrading our server to version 3.0.0.9 and have run into the same problem. this error is due to mysql database upgrade from 10.1xx to 10.7.xx. resolved with this guide. https://mariadb.com/kb/en/troubleshooting-row-size-too-large-errors-with-innodb/

**Comment by nilsteampassnet** [comment]
Thank you @basfeo 👍

**Comment by geokh** [comment]
Dear all,
i managed to do it by running : 

https://stackoverflow.com/questions/51250156/how-to-apply-row-format-dynamic-to-an-existing-table
SET GLOBAL innodb_file_format=Barracuda;
   SET GLOBAL innodb_file_per_table=1;
   SET GLOBAL innodb_large_prefix=1;
   logout & login (to get the global values);
   ALTER TABLE tbl ROW_FORMAT=DYNAMIC;  -- (or COMPRESSED)

But now with version 3.0.0.9 the LDAP is not working any new update?

Alert!
The LDAP PHP extension is not loaded on the server.

**Comment by abcqwertz** [comment]
Additional information for those who also run into this issue.
I had the same message when i upgraded to 3.0.22:
`2023-01-20 13:38:21 144 [ERROR] InnoDB: Cannot add field `name` in table `teampass`.`teampass_users` because after adding it, the row size is 8243 which is greater than maximum allowed size (8126 bytes) for a record on index leaf page`
To change the row format to DYNAMIC fixed the issue for me:
`2023-01-20 13:38:21 144 [ERROR] InnoDB: Cannot add field `name` in table `teampass`.`teampass_users` because after adding it, the row size is 8243 which is greater than maximum allowed size (8126 bytes) for a record on index leaf page`
