### ISSUE TITLE
error after instalation and cannot dispaly index.php

### ISSUE THREAD

**Issue by nulldayexploits** [nilsteampassnet/TeamPass#3057]
PHP Warning:  include(../../../config/tp.config.php): failed to open stream: No such file or directory in /home/hrms8571/public_html/TeamPass-master/includes/libraries/Database/Meekrodb/db.class.php on line 979
PHP Warning:  include(): Failed opening '../../../config/tp.config.php' for inclusion (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') in /home/hrms8571/public_html/TeamPass-master/includes/libraries/Database/Meekrodb/db.class.php on line 979
PHP Warning:  include_once(/includes/libraries/protect/SuperGlobal/SuperGlobal.php): failed to open stream: No such file or directory in /home/hrms8571/public_html/TeamPass-master/sources/main.functions.php on line 1513
PHP Warning:  include_once(): Failed opening '/includes/libraries/protect/SuperGlobal/SuperGlobal.php' for inclusion (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') in /home/hrms8571/public_html/TeamPass-master/sources/main.functions.php on line 1513
PHP Warning:  include_once(/sources/SplClassLoader.php): failed to open stream: No such file or directory in /home/hrms8571/public_html/TeamPass-master/sources/main.functions.php on line 1524
PHP Warning:  include_once(): Failed opening '/sources/SplClassLoader.php' for inclusion (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') in /home/hrms8571/public_html/TeamPass-master/sources/main.functions.php on line 1524

**Comment by nilsteampassnet** [comment]
PLease be kind, provide some useful data to investigate on

**Comment by ewheelerinc** [comment]
Hello Nils,

We have the same problem when trying to move to 2.1.27.36 to 3.0.0.14 which we are using from the tip of master which is currently 9e47e567fdd2b8bd1a15e0ddb372753b946e01b1 .

We get the following errors when trying to load the front page after moving the database:

```

Warning: include(../../../config/tp.config.php): failed to open stream: No such file or directory in /var/www/TeamPass/includes/libraries/Database/Meekrodb/db.class.php on line 979

Warning: include(): Failed opening '../../../config/tp.config.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/TeamPass/includes/libraries/Database/Meekrodb/db.class.php on line 979

Warning: include_once(/includes/libraries/protect/SuperGlobal/SuperGlobal.php): failed to open stream: No such file or directory in /var/www/TeamPass/sources/main.functions.php on line 1519

Warning: include_once(): Failed opening '/includes/libraries/protect/SuperGlobal/SuperGlobal.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/TeamPass/sources/main.functions.php on line 1519

Warning: include_once(/sources/SplClassLoader.php): failed to open stream: No such file or directory in /var/www/TeamPass/sources/main.functions.php on line 1530

Warning: include_once(): Failed opening '/sources/SplClassLoader.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/TeamPass/sources/main.functions.php on line 1530

```

If we go to line 979 in Meekrodb/db.class.php and do `echo getcwd()` it shows that it is running in /var/www/TeamPass (the document root) so trying to include `../../../config/tp.config.php` is of course not going to find anything.

When we hack Meekrodb/db.class.php to `includes/config/tp.config.php` instead, the front page is all white and there are no Apache or console errors.

When we try to follow the upgrade process at the install/upgrade.php page, after entering the credentials and hitting `START`, it just spins and the following console error is displayed in Firefox:

```

Uncaught SyntaxError: JSON.parse: expected ',' or '}' after property value in object at line 2 column 71 of the JSON data
    complete https://teampass.ewi/install/upgrade.php:216
    jQuery 6
    <anonymous> https://teampass.ewi/install/upgrade.php:208
    jQuery 9
    <anonymous> https://teampass.ewi/install/upgrade.php:151
    jQuery 13


```

This is the response from the post:

```

[{ "error" : "Impossible to get connected to server. Error is: " . addslashes(mysqli_connect_error()), "index" : "" }]

```

so it sounds like we have a database connection problem. It would be nice to get a friendly error indicating that since not everyone knows how to debug web applications.

The way we deployed this installation was to do a fresh install and then replace the database. We are using the same salt key from the old server (/var/lib/teampass/teampass-seckey.txt) and specified it during the install process.

The setting in includes/config/settings.php that defined the password for the database was a long encrypted hash so we replaced it with the actual database password and now we can click `START` and continue the upgrade process.

We are currently proceeding with the upgrade process and will let you know what we discover.
