### ISSUE TITLE
php requirement not associate php gd and php xml

### ISSUE THREAD

**Issue by BenoitPel** [nilsteampassnet/TeamPass#3293]
teampass version 3.0.0.17
new installation
on page to verify if all module are loaded i see in same line : php extension gd is loaded Extension xml is not loaded.
Maybe do another line to this :)

**Comment by nratineau** [comment]
@BenoitPel Hi! Thank you for reporting. Can you provide a screenshot of what you mean?
Thanks again!

**Comment by Kyogre** [comment]
> Can you provide a screenshot of what you mean?
hi! I can provide it if OP still don't. Here it is:

![teampass install Extension xml is not loaded](https://user-images.githubusercontent.com/2260980/216308827-783370bd-2df2-476f-b219-938ddb6c2cee.png)

If I am correct such error happens because you haven't installed `php-xml` package for your `php` version.
FYI I can't install my `php-xml` package because, when I trying `dnf install php81-php-xml`, I get an error
`cannot install the best candidate for the job
  - nothing provides libgcrypt.so.11()(64bit) needed by php81-php-xml-8.1.14-1.el7.remi.x86_64`

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.
