### ISSUE TITLE
Optimization for tree load with many folders

### ISSUE THREAD

**Issue by alarido** [nilsteampassnet/TeamPass#3478]
With the same functionality there are some queries that can be optimized, counting elements inside a folder now use a full select with all columns and then a PHP function to calculate the count, that takes in my system around 0.02s per query but 1000 queries requires 20s which makes tree load slow.

Reducing columns fetched or directly allowing mysql to calculate the number of elements is faster 0.003s per query, 1000 queries requires then 3s which is much faster.

Other possible optimization would be remove the element count altogether, then tree is created pretty fast, now there is a possibility to enable/disable detailed count of elements as it has a big impact in performance, I don't know how difficult would be to add an option to disable completely the count but it would be interesting.

This patch should improve performance keeping the same functionality:

```
diff tree.php.orig tree.php
287,288c287,288
<     DB::query(
<         'SELECT *
---
>     $ret['itemsNb'] = (int) DB::queryfirstrow(
>         'SELECT COUNT(*) AS num_results
293,294c293
<     );
<     $ret['itemsNb'] = DB::count();
---
>     )['num_results'];
297,298c296,297
<     DB::query(
<         'SELECT *
---
>     $ret['childrenNb'] = (int) DB::queryfirstrow(
>         'SELECT COUNT(*) AS num_results
302,303c301
<     );
<     $ret['childrenNb'] = DB::count();
---
>     )['num_results'];
379,380c377,378
<             DB::query(
<                 'SELECT * FROM ' . prefixTable('items') . '
---
>             $nbChildrenItems = (int) DB::queryfirstrow(
>                 'SELECT COUNT(*) AS num_results FROM ' . prefixTable('items') . '
384,385c382
<             );
<             $nbChildrenItems += DB::count();
---
>             )['num_results'];
466,467c463,464
<     DB::query(
<         'SELECT * FROM ' . prefixTable('items') . '
---
>     $itemsNb = (int) DB::queryfirstrow(
>         'SELECT COUNT(*) AS num_results FROM ' . prefixTable('items') . '
471,472c468
<     );
<     $itemsNb = DB::count();
---
>     )['num_results'];
851c847
< }
\ No hay ningún carácter de nueva línea al final del fichero
---
> }

```

This patch it's a dirty hack to not make folder count queries and will show all folder count as "0" load it's much faster but as I said it's not pretty, just a hack:

```
287,288c287,289
<     DB::query(
<         'SELECT *
---
> /*
>       $num_results = DB::queryfirstrow(
>         'SELECT COUNT(*) AS num_results
294c295,297
<     $ret['itemsNb'] = DB::count();
---
>     $ret['itemsNb'] = (int) $num_results['num_results'];
> */
>     $ret['itemsNb'] = 0;
297c300,301
<     DB::query(
---
> /*
>     $num_results = DB::queryfirstrow(
303c307,309
<     $ret['childrenNb'] = DB::count();
---
>     $ret['childrenNb'] = (int) $num_results['num_results'];
> */
>     $ret['childrenNb'] = 0;
379,380c385,387
<             DB::query(
<                 'SELECT * FROM ' . prefixTable('items') . '
---
> /*
>             $num_results = DB::queryfirstrow(
>                 'SELECT COUNT(*) AS num_results FROM ' . prefixTable('items') . '
385c392,394
<             $nbChildrenItems += DB::count();
---
>             $nbChildrenItems += (int) $num_results['num_results'];
> */
>             $nbChildrenItems += 0;
466,467c475,477
<     DB::query(
<         'SELECT * FROM ' . prefixTable('items') . '
---
> /*
>     $num_results = DB::queryfirstrow(
>         'SELECT COUNT(*) AS num_results FROM ' . prefixTable('items') . '
472c482,484
<     $itemsNb = DB::count();
---
>     $itemsNb = (int) $num_results['num_results'];
> */
>     $itemsNb = 0;


```

**Comment by eduardomozart** [comment]
I also noticed that when opening a folder with a lot of items (80) and selecting one to show it's item details, it still keep loading the remaining items of the folder (as can be seen at the Chrome console), even when we are already selected one item at the folder. I believe there should be an AJAX improvement for it doesn't happen to decrease the DB, bandwidth and CPU usage.
I've already reported a lot of Teampass bugs and helped other users to fix bugs into their instances, but the v3 release of Teampass is so troublesome and the most relevants bug reports doesn't seem to be fixed (I know that it's only one person working actively into this project and understand that it's free, so I'm not complaining, just standing my opinion about the current Teampass state), that I've decided to migrate to sysPass yesterday. I really liked the Plugin architecture that sysPass have (so I could change it's core functionality without losing it when upgrading the sysPass version), and I could easily deploy it's changes for other customers and other people that uses sysPass, that can contribute with the changes I've made and make it better - in Teampass it's more difficult because any changes requires changing the source code directly and manual approval of the changes by the only one person that's working into this project, and setup 2FA into sysPass seams to be more easily than into Teampass itself. Teampass has more OTP integration options and seems more secure by using a different architecture than sysPass (sysPass uses a Master Password to encrypt all passwords at the DB), but the Teampass bugs at the v3 are so troublesome that I've decided to move on to sysPass.

**Comment by alarido** [comment]
If I remember correctly you can avoid that behavior disabling the copy user/password/.., buttons in the password item list.

Nothing is perfect, I am grateful to have a project like teampass to rely on and also in all the effort that Nils has been pouring over it along the years that's why if I find a way to improve it even if it's a little a will do it within my possibilities.

I will look into syspass but teampass work well for me.

**Comment by nilsteampassnet** [comment]
Have you set this option to No
![image](https://user-images.githubusercontent.com/1197546/212546486-9efbfc26-879d-444a-8f08-57a2909904a4.png)

**Comment by nilsteampassnet** [comment]
I will propose a change considering option "show more counters".
If enabled then you see all.
If not, you don't have counter at all.
Based upon your code, I will improve this.
Thanks

**Comment by alarido** [comment]
Yes, I have that option usually disabled, the proposed alternative to count elements helps with simple an detailed counters, usually with simple counte of elements I see around 1k queries counting elements, that's why reducing by one order of magnitude every query makes a big difference.
> Have you set this option to No ![image](https://user-images.githubusercontent.com/1197546/212546486-9efbfc26-879d-444a-8f08-57a2909904a4.png)

I think It 's a good idea, counters are not so important, the most important thing is being able to organize passwords in folders and I can tell that without them load it's much faster.
> I will propose a change considering option "show more counters". If enabled then you see all. If not, you don't have counter at all. Based upon your code, I will improve this. Thanks

Thank you very much :)
