### ISSUE TITLE
Creating a new folder seems to not finish

### ISSUE THREAD

**Issue by whosht** [nilsteampassnet/TeamPass#3751]
### Steps to reproduce
1. Login
2. (Goto "Password" Section)
3. Select drop down menu in "Folder" area and click on "Add"
4. Specify "Label" and "Select parent folder"
5. Click "Perform"

### Expected behaviour
Dialog closes and the tree shows new folder in expected parent.

### Actual behaviour
Dialog doesn't close.
Web-Developer console says "Internal Server error"
Apache error log  shows error.
Aborting Dialog and refreshing page shows folder in correct position

### Server configuration
**Operating system**: Debian 11

**Web server:** apache2 2.4.56-1~deb11u2

**Database:** mariadb-server 1:10.5.19-0+deb11u2

**PHP version:** php 7.4.33-1+deb11u3

**Teampass version:** 3.0.9 (2b998b6a0f69df7bf98d2c148238e75f0f8bd402)

**Teampass configuration file:** I will update it if it is really relevant.

**Updated from an older Teampass or fresh install:** Updated from older Teampass

### Client configuration
**Browser:** Firefox

**Operating system:** Windows 10

#### Web server error log
```
[Tue Jun 06 15:22:37.354836 2023] [php7:error] [pid 501743] [client 192.168.1.203:60597] PHP Fatal error:  Uncaught TypeError: explode() expects parameter 2 to be string, array given in /var/www/html/teampass/sources/main.functions.php:3840\nStack trace:\n#0 /var/www/html/teampass/sources/main.functions.php(3840): explode()\n#1 /var/www/html/teampass/sources/folders.queries.php(830): getUsersWithRoles()\n#2 {main}\n  thrown in /var/www/html/teampass/sources/main.functions.php on line 3840, referer: https://pw.who-ing.local/index.php?page=items
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by AKorolkovs** [comment]
Have similar issue.
User can't create any folder. Following error thrown in log:
`[Thu Jul 06 09:44:38.259135 2023] [proxy_fcgi:error] [pid 21373] [client 10.128.149.84:53246] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: explode(): Argument #2 ($string) must be of type string, array given in /var/www/teampass.hostname.com/sources/main.functions.php:3854\nStack trace:\n#0 /var/www/teampass.hostname.com/sources/main.functions.php(3854): explode()\n#1 /var/www/teampass.hostname.com/sources/folders.queries.php(832): getUsersWithRoles()\n#2 {main}\n  thrown in /var/www/teampass.hostname.com/sources/main.functions.php on line 3854', referer: https://teampass.hostname.com/index.php?page=items`

After that user can't create any item because Parent Folder list is empty

**Comment by whosht** [comment]
Works now after having:
* updated to 3.0.10.81
* installed a few php modules (see composer.json in one of the latest commits (958ca2b)
* updated to Debian 12 (at least php 8.1 is needed)
