### ISSUE TITLE
Configured LDAP settings not used when authenticating

### ISSUE THREAD

**Issue by funkypenguin** [nilsteampassnet/TeamPass#394]
Hi,

I'm running 2.1.18, and configured my LDAP settings with use_ssl=1, LDAP domain controllers, and a base DN.

I enable ldap debugging, and the ldap debug log shows:

```
Get all ldap params :
base_dn :
account_suffix :
domain_controllers :
use_ssl : 
use_tls :
*********

Create new adldap object : Success


After authenticate : Can't contact LDAP server


ldap status :
```

As you can see, the base_dn, use_ssl, domain_controllers values are all blank, and so authentication is not working. (Can't contact the LDAP server because no LDAP server was recognised)

I dumped the MySQL database, and examined the settings data, and found that the values were correctly set. However, they don't seem to be read correctly when trying to do an LDAP auth.

Any ideas?
Thanks,
D

**Comment by funkypenguin** [comment]
FWIW, either you or I must have resolved this, since we've been using LDAP auth in prod for years now ;)

**Comment by nilsteampassnet** [comment]
I don't have your knowledge of LDAP and so many configuration exist.
Neverhteless Teampass uses a very used PHP library to handle LDAP authentication that is called adLDAP.

Perhaps, do you need to adapt your configuration.
If TEampass returns that it cannot contact the LDAP server, it means that there is an error or at least something that is entered in a format that adLDAP consideres as wrong.

I'm in contact with a lot of users that are using LDAP authentication. So there must be a way to configure.

Perhaps can you share your configuration and logs so that users can help you?
