### ISSUE TITLE
Backup script does not working.

### ISSUE THREAD

**Issue by kristofkad** [nilsteampassnet/TeamPass#443]
Hi. I am running Ubuntu 12.04 Server with XAMPP stack and I'm using TeamPass 2.1.18. I have some problems with backups. When i'm using "One shot backup" it works great (i'm getting a .sql file and can save it). But now i want to automate my backups. I see, that there is a script.backup.php in /opt/lampp/htdocs/teampass/backups directory. And that is my setting in teampass. 
![tp](https://f.cloud.github.com/assets/5766744/1559182/1765cbf8-4fc1-11e3-8856-aaf42c572eb1.jpg)
But when i'm running "sudo php script.backup.php" it just does not create any backup files. Script is launching without errors and /backups folder have all permissions. I also tried to change backup folders and the name of files in teampass, but didn't get any positive result. 

Thanks,
Andrei

**Comment by wbcsaint** [comment]
I know this issue is 2 years old but I just experienced it and found the resolution. Even if you want to store the backups in the default location listed on the settings page (/installpath/backup), you have to remove it and re-enter it so that it actually saves it to the misc table in the database. It is the same thing with the backup file name. It looks like even though those fields are populated it doesnt save them to the misc table unless you actually change them first.  Once I changed them a cut and paste of the same string back into the box, running the php script for backups worked perfect.

**Comment by nilsteampassnet** [comment]
thanks
