### ISSUE TITLE
Offline mode hang

### ISSUE THREAD

**Issue by perceau** [nilsteampassnet/TeamPass#513]
Hello,

I just begun testing your great product.
one key function is the ability to securely export password

when i try it,no reply from the webbrowser !
i find this in apache access_log : 
10.49.70.47 - - [18/Feb/2014:13:51:40 +0100] "POST /TeamPass-master/sources/export.queries.php HTTP/1.1" 500 - "http://teampass.eram.loc/TeamPass-master/index.php" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36"
10.49.70.47 - - [18/Feb/2014:13:52:08 +0100] "POST /TeamPass-master/sources/export.queries.php HTTP/1.1" 500 - "http://teampass.eram.loc/TeamPass-master/index.php" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.107 Safari/537.36"

can't find the reason of error code 500

**Comment by sjaredj** [comment]
I recently installed version 2.1.22 and when I try to export to use in off-line mode I get a 500 error in apache access logs

[03/Feb/2015:10:51:08 -0700] "POST /teampass/sources/export.queries.php HTTP/1.1" 500 -

It sits there and acts like it is doing something (the 3 bars indicating progress continue to move) but I never get the download button to appear.  I have selected a single folder (which is a subfolder of a parent folder) with only 3 passwords being stored in it.  So it appears what ever the issue it still exists.  

blastik says in a post above that he could select PDF rather than HTML.  I don't see where that option is.  Is it something I need to enable as admin?  A quick glimpse at settings as admin user didn't reveal any export settings.  Am I just not seeing it?

I have users that would really benefit from this off-line mode.  Can someone point out if I am doing something wrong?

**Comment by sjaredj** [comment]
Ok I found what I think he is talking about with PDF.  There is a setting that allows users to print paswords to a pdf file.  This leaves them unencrypted.  This will not do for us.  I need the ability to encrypt the export file.  Any suggestions?

**Comment by sjaredj** [comment]
update:
I just upgraded to 2.1.23.  Although the off-line mode popup looks a little fancier (a rotating gear rather then the 3 bars moving) it still never returns.  Any help here would be appreciated.

**Comment by faregran** [comment]
Same here: never ending rotating gear even with 1 empty folder; error 500 in log:

10.111.1.65 - - [30/Mar/2015:17:05:25 +0200] "POST /teampass/sources/export.queries.php HTTP/1.1" 500 425 "http://10.111.1.85/teampass/index.php?page=items&session_over=true" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:36.0) Gecko/20100101 Firefox/36.0"

**Comment by mr-gosh** [comment]
any progress here?
i'm feeling bad - not having the ability to export the database to view it in an offline reader... (like keepass)
