### ISSUE TITLE
email teampass vers.2.1.19patch

### ISSUE THREAD

**Issue by anaisro** [nilsteampassnet/TeamPass#541]
Hi, 
I'm sorry for my bad english, i'm french... but i've a problem with the email configuration. 
I've install teampass on the ubuntu server, i've in my network a email server. 

When I give informations about my server smtp : 
serveur smtp : mail.znale.fr
SMTP server needs authentification : yes
Authentification Username : me@znale.fr
Authentification Password: mypassword
Server Port : 587
Sender Email (from Email) : me@znale.fr
Sender Name (from Name) : me

I've this error message : 
Email not sent ... check your configuration. See associated error:  SMTP Error: The following recipients failed:

I'dont understand... teampass ' email requiere a package ? 
I've not installing a email server in my teampass server. 
Teampass use LDAP authentication. 
I've not a error in syslog and i ping mail.znale.fr

Thanks for your help ... I hope for my message is understandable. 

regards, 

Anaïs

**Comment by moraski** [comment]
Im having this same problem.
I receive the test mail perfectly, but the emails stay at the database as not sent...
Have someone found whats causing this error?

**Comment by Reeslo** [comment]
Same issue with gmail addresse, and without :+1: 
I have this response with gmail addresse with port 25/465/587
```
[{"result":"email_test_conf", "error":"error_mail_not_send" , "message":"SMTP Error: Could not connect
 to SMTP host."}]
```

**Comment by Reeslo** [comment]
With $mail->debug = 1 
```
SMTP -> ERROR: Failed to connect to server: Connection timed out (110)
[{"result":"email_test_conf", "error":"error_mail_not_send" , "message":"SMTP Error: Could not connect
 to SMTP host."}]
```

**Comment by niomax76** [comment]
Hello , i read this only now... and i have the same problem as Raquel3s , ( test mail work ...fine) but Email for user login and notification when item is shown doesn't work.... Some advice to solve this problem ?

**Comment by weltzien** [comment]
Hi,

i have the same problem, but if i use the "resend" button it works.

but this is no solution for me.

**Comment by sitzmoebelchronograph** [comment]
Hey guys,

i'm not sure, this place are the correct one, because of old topic and new entries. I could open a new request with right version topic, if needed.

But i could also confirm this "bug". I'm using version 2.1.26 and want to have Email notification for login's. The emails stored in database but arn't send to admins email address. 
By using the resend button the stored mails going out.

So test and resend buttons are working, the mail configuration looks like ok.

The issue looks like an missing or broken "cronjob" or "now send action" in teampass.

@nilsteampassnet did you need some more informations about this?

best 

Andy
