### ISSUE TITLE
Configuration in HA

### ISSUE THREAD

**Issue by xFRaNeRx** [nilsteampassnet/TeamPass#779]
Hello,

We are trying to deploy TeamPass as a High Availability solution. We have tried to use two frontends (web server) and a multimaster galera cluster of mysql, balanced by an HAProxy, but it doesn't works. There are errors in mysql.

There are some recommended configuration to do an Teampass HA deployment?

Thanks in advance,
Fran

**Comment by fullmoon4465** [comment]
I have a similar issue. I am using galera + mariadb on ubuntu 12.04 x64. My issue isn't load balancing since its a multi-master setup so I have bypassed my load balancer (maxscale) all together. Database is replicated fine as its alread a InnoDB type. Collation's look fine. Permissions look fine. I was able to update all dependencies during install and seemed successful. However now when first trying to hit the page after install, I get an error "You are not allowed to see this page." in chrome, but a 500 error in IE. I don't see any debugging options other then ldap.

**Comment by fullmoon4465** [comment]
I take that back... I just downloaded 2.1.26_RC1 and did a fresh install on the front end, but left the back end alone. Seems fine and now pages pull up. I noticed languages has values in it now on the db so that "may" have been my issue. Please disregard my comments since new version seems fine.

**Comment by fullmoon4465** [comment]
Well for whomever reads hits, I had to add a column for can_manage_all_users in the database for it to work. This really isn't the place for this note, but helpful non the less to others
