### ISSUE TITLE
can not create Admin account

### ISSUE THREAD

**Issue by madjuran** [nilsteampassnet/TeamPass#950]
I can't install teampass, connection to the database is 0k, user is 0k, I try with root user, and tpadmin, and it's the same error. All privileges are granted, and I can do everything from console, but from GUI does not work.
![teampassadminaccount](https://cloud.githubusercontent.com/assets/11291292/7019864/840f5df0-dd14-11e4-8eab-d16dad8c21e2.png)

**Comment by madjuran** [comment]
No errors in firebug...
![firebug](https://cloud.githubusercontent.com/assets/11291292/7019961/6cb8dfa4-dd15-11e4-88e5-6afe0fba857e.png)

**Comment by madjuran** [comment]
error from apache log
[Tue Apr 07 09:03:06 2015] [error] [client ipaddress] PHP Notice:  Undefined offset: 1 in /var/www/html/teampass/sources/sessions.php on line 113, referer: http://teampass.mydomain.com/install/install.php
(END)

**Comment by madjuran** [comment]
Finaly, I was install teampass at local machine, everything was all right, then I export admin user from teampass_users table and import to problematic...

**Comment by Revolutio** [comment]
Error is, that avatar and avatardir (I think this is the right name... hav no database in front of me) has no default value...

So the user cannot be created..

**Comment by madjuran** [comment]
Thank you, so what would be default value?

**Comment by Revolutio** [comment]
I changed it here from NOT NULL to NULL... 

But I don't know whether this create new issues

**Comment by madjuran** [comment]
There are two avatar* fields, when I change avatar, it's the same, but when I change avatar_thumb from NULL to 0, it's 0k, admin user is created, installation successfully ended. But, I can't create new user...

**Comment by prozit** [comment]
As described by Revolutio, you can alter the table teampass_users (if you kept the default prefix setting on teampass_) and modify the avator column and the avatar_thumb column to NULL instead of NOT NULL.

The following commands should be run in MySQL for example (if database name = teampass and prefix is set to teampass_):

use teampass;
alter table teampass_users modify avatar varchar(255) NULL;
alter table teampass_users modify avatar_thumb varchar(255) NULL;

After that, launch creation again (not restart) and you should be OK.
I believe this is a small bug in the table creation of this Teampass version.

You can check the column settings by using the commands
use teampass;
describe teampass_users;

Before altering the table that should give you the first screenshot, after altering, it should give you the second one.

![teampass-database-wrong-structure](https://cloud.githubusercontent.com/assets/8732366/7387855/01b5671a-ee61-11e4-9cef-12a6b1421ca2.png)

![teampass-database-corrected-structure](https://cloud.githubusercontent.com/assets/8732366/7387857/076a2ccc-ee61-11e4-9b96-2fe49a39a901.png)

**Comment by Revolutio** [comment]
the problem is at the creation of the table...
Many more fields has to be set Nullable, because of user creation in the adminpanel afterthat.

![teampass_mysql](https://cloud.githubusercontent.com/assets/10235033/7388103/da993e52-ee62-11e4-9409-a461555e9746.png)

Maybe I have time this evening to write a bugfix...

**Comment by madjuran** [comment]
When do everything you say, I can create admin, and after that users, but when I login with any other user except admin, I get the following page:
![teamass_last_error](https://cloud.githubusercontent.com/assets/11291292/7565307/492cca74-f7ef-11e4-9459-40cccf08cddd.png)

This is my teampass_users table:
![teampass_users_table](https://cloud.githubusercontent.com/assets/11291292/7565346/831cd4f4-f7ef-11e4-9a2f-3301d70dd6ef.png)
