### ISSUE TITLE
TeamPass 2.1.23

### ISSUE THREAD

**Issue by malikanique** [nilsteampassnet/TeamPass#991]
can't see the items in folders
can you tell me how to slove this problem...
But when i search it by name it appears....

![image](https://cloud.githubusercontent.com/assets/12664882/8204376/6838266e-14e8-11e5-9a87-1c2bac62493a.png)

**Comment by malikanique** [comment]
any body can help me?

**Comment by nilsteampassnet** [comment]
Please can you provide the error log from apache server? 
Or a message from Firebug?

**Comment by malikanique** [comment]
There are nothing in the nginx errorlog. I can only see the GET in the access log. We are working with Nginx not Apache.

In Firebug we see this error messages:
POST https://*****.com/sources/main.queries.php
	
200 OK
		27ms	
jquery.js (line 8706)
HeadersPostResponseHTMLCookies

[{"error" : "" , "text" : "<li onclick=\"displayItemNumber(1, 2)\"><i class=\"fa fa-tag fa-fw\"></i>
 &nbsp;xavier@seraph</li><li onclick=\"displayItemNumber(2, 4)\"><i class=\"fa fa-tag fa-fw\"></i> &nbsp
;root@mimbre</li>"}]

POST https://*********.com/sources/items.queries.php
	
200 OK
		36ms	
jquery.js (line 8706)
HeadersPostResponseHTMLCookies

Error: <br>
Query: SELECT i.id as id, i.restricted_to as restricted_to, i.perso as perso,
                        i.label as label, i.description as description, i.pw as pw, i.login as login
,
                        i.anyone_can_modify as anyone_can_modify, l.date as date,
                        n.renewal_period as renewal_period,
                        l.action as log_action, l.id_user as log_user,
                        k.rand_key as rand_key
                        FROM items as i
                        INNER JOIN nested_tree as n ON (i.id_tree = n.id)
                        INNER JOIN log_items as l ON (i.id = l.id_item)
                        LEFT JOIN keys as k ON (k.id = i.id)
                        WHERE (i.id_tree=1) AND (i.inactif=0) AND (l.action='at_creation')
                        GROUP BY i.id
                        ORDER BY i.label ASC, l.date DESC LIMIT 0,11<br>

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
	

return window.JSON.parse( data );

**Comment by niallfleming** [comment]
I'm seeing this issue too.

**Comment by malikanique** [comment]
can you help us to solve this problem ??

**Comment by niallfleming** [comment]
This issue was solved for me by the following patch:

diff --git a/items.load.php b/items.load.php
index 093740a..887b365 100644
--- a/items.load.php
+++ b/items.load.php
@@ -1966,7 +1966,7 @@ $(function() {
     }
 
     //Evaluate number of items to display - depends on screen height
-    if (parseInt($("#nb_items_to_display_once").val()) || $("#nb_items_to_display_once").val() == "max") {
+    if (parseInt($("#nb_items_to_display_once").val())) { // || $("#nb_items_to_display_once").val() == "max") {
         //do nothing ... good value
     } else {
         //adapt to the screen height
diff --git a/sources/identify.php b/sources/identify.php
index dbf5a2e..70c0108 100644
--- a/sources/identify.php
+++ b/sources/identify.php
@@ -191,6 +191,15 @@ function IdentifyUser($sentData)
             // authenticate the user
             if ($adldap->authenticate($auth_username, html_entity_decode($passwordClear))) {
                 $ldapConnection = true;
+		//update user's password
+                $data['pw'] = $pwdlib->createPasswordHash($passwordClear);
+                DB::update(prefix_table('users'),
+                    array(
+                        'pw' => $data['pw']
+                    ),
+                    "login=%s",
+                    $username
+                );
             } else {
                 $ldapConnection = false;
             }
@@ -251,7 +260,7 @@ function IdentifyUser($sentData)
             prefix_table('users'),
             array(
                 'login' => $username,
-                'pw' => $password,
+		'pw' => $pwdlib->createPasswordHash($passwordClear),
                 'email' => "",
                 'admin' => '0',
                 'gestionnaire' => '0',
diff --git a/sources/items.queries.php b/sources/items.queries.php
index 85333ec..befed2f 100644
--- a/sources/items.queries.php
+++ b/sources/items.queries.php
@@ -1822,13 +1822,14 @@ if (isset($_POST['type'])) {
                         $where
                     );
                 } else {
-                    $items_to_display_once = "max";
+                    //$items_to_display_once = "max";
                     /*
                     if ($items_to_display_once != 'max') {
                         $query_limit = " LIMIT ".$start.",".$items_to_display_once;
                     } else {
                         $query_limit = "";
                     }*/
+		    // current folder is PF
 
                     $rows = DB::query(
                         "SELECT i.id as id, i.restricted_to as restricted_to, i.perso as perso,
@@ -2106,7 +2107,7 @@ if (isset($_POST['type'])) {
             $counter = DB::count();
         	// DELETE - 2.1.19 - AND (l.action = 'at_creation' OR (l.action = 'at_modification' AND l.raison LIKE 'at_pw :%'))
             // Check list to be continued status
-            if (($items_to_display_once + $start) < $counter && $items_to_display_once != "max") {
+            if (($items_to_display_once + $start) < $counter) { // && $items_to_display_once != "max") {
                 $listToBeContinued = "yes";
             } else {
                 $listToBeContinued = "end";
@@ -3076,4 +3077,4 @@ function passwordReplacement($pw)
     $pwRemplacements = array('&', '+');
 
     return preg_replace($pwPatterns, $pwRemplacements, $pw);
-}
\ No newline at end of file
+}

**Comment by niallfleming** [comment]
This was cribbed from another post on here.

Incidentally, I'm not sure why these fixes which would seem to apply to everyone are not merged into the .23 branch as a hotfix. Stable doesn't seem to be all that stable :(

**Comment by rstoever** [comment]
Hi,
I don't understand this fixed, because ? I upgrade from 2.1.22 to 2.1.23 and my environment stay equal to issue of malikanique.
I had to restore backup to 2.1.22.
:(
