### ISSUE TITLE
Cannot create new user

### ISSUE THREAD

**Issue by dorianmuthig** [nilsteampassnet/TeamPass#994]
Version: 2.1.23-Release

When signed in as admin, directly after installation, I am unable to create a user.
The web app first sends an AJAX request like this:

**Request**

``` http
POST /TeamPass/sources/users.queries.php HTTP/1.1
Host: localhost
Connection: keep-alive
Content-Length: 36
Accept: */*
Origin: http://localhost
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2431.0 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Referer: http://localhost/TeamPass/index.php?page=manage_users
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8
Cookie: PHPSESSID=d0b73ab8a2315035c3a69ea60e92e721; KEY_PHPSESSID=OWSJjHzjgaDZULAh3cg3AgxmpxkAOMiLYYCzhAi%2BS4s%3D%3AaSebWMMwk95sCBbF94YEUs%2BSQy59Grb3AvLJ%2BWXU%2Bss%3D
```

```
type=check_domain&domain=example.com
```

**Response**

``` http
HTTP/1.1 200 OK
Date: Sat, 20 Jun 2015 18:15:14 GMT
Server: Apache/2.4.10 (Unix) PHP/5.6.10
X-Powered-By: PHP/5.6.10
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Length: 43
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=utf-8
```

``` javascript
{"folder":"not_exists","role":"not_exists"}
```

After which it sends another request as follows:

**Request**

``` http
POST /TeamPass/sources/users.queries.php HTTP/1.1
Host: localhost
Connection: keep-alive
Content-Length: 484
Accept: application/json, text/javascript, */*; q=0.01
Origin: http://localhost
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2431.0 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Referer: http://localhost/TeamPass/index.php?page=manage_users
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8
Cookie: PHPSESSID=d0b73ab8a2315035c3a69ea60e92e721; KEY_PHPSESSID=OWSJjHzjgaDZULAh3cg3AgxmpxkAOMiLYYCzhAi%2BS4s%3D%3AaSebWMMwk95sCBbF94YEUs%2BSQy59Grb3AvLJ%2BWXU%2Bss%3D
```

``` uri
type=add_new_user&data=sq2FVSIiIiKrCrZj0%2Fq82rk8tyAA2I9EHLshQnnovbnw%2BBdP1DDTg2CbktSqnGzsnsJj%2Fq5cgrXfAE1HBso8ECvTW1YJ4S%2BFM7arePcs%2B%2BKuwuy067SC7l8dcutdeiDkHYa5ScLJ%2F63VHGL8RjCD0b1A7gzB9YuG4vyXeI%2BFQ%2B3VF4NUQplAM8ZI%2F23%2BqrRuyM6isQcDRbm%2FH03%2Ft1nfzFTMHWFjTQjy%2Fl7zo9RBGf1xi0TyghA6hmNbbsxkMv8voQ5FF63IUYbLM1zKFT4%2F4HidchVgL3KErcVu8ec1d6B7BhHUv8Ieebq6j68032jMNQNR0wtUFq2N4b%2FQxh5WMtrDuh5k7C%2B6xOYFJNOdtRtuuGM%3D&key=llx61bw6X3k709HpUhaIw832plJyhZ6.DO%2F78WLs0iR5qJL9I9
```

**Response**

``` http
HTTP/1.1 200 OK
Date: Sat, 20 Jun 2015 18:15:14 GMT
Server: Apache/2.4.10 (Unix) PHP/5.6.10
X-Powered-By: PHP/5.6.10
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Length: 405
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive
Content-Type: text/html; charset=utf-8
```

``` sql
Error: <br>
Query: INSERT INTO `teampass_users` (`login`,`name`,`lastname`,`pw`,`email`,`admin`,`gestionnaire`,`read_only`,`personal_folder`,`user_language`,`fonction_id`,`groupes_interdits`,`groupes_visibles`,`isAdministratedByRole`) VALUES ('test', 'test', 'test', '$2y$13$c88f9699cccfe8b725478uL2VHU/sbS5c0ttAIFCUqIHmtdwfzMHe', 'test@example.com', '0', '1', '0', '1', 'english', '', '0', '0', '0')<br>
```

The user interface does absolutely nothing to indicate that something went wrong. I'm sure I don't have to mention that returning SQL queries is a bad idea. This is supposed to be security software, right?

If this issue presents, because I have no valid email server set up and used an invalid email address to create the user, I find considerable issue with this, because it should be possible to do this.

**Comment by nilsteampassnet** [comment]
IT sends back the data because of an error!
For good security, you should any how use a valid SSL connection.

Anyway, the insert error you get is very strange. Does the table exists in your database?

**Comment by dorianmuthig** [comment]
It should not send back the data, this could enable a user to discover the data structure, leak server side information the user would ordinarily never get to see, or make an SQL injection vulnerability readily apparent. SQL connection and query errors should never be returned to the user. They should be logged silently for review by an administrator. This is a local test installation not intended for production use, therefore TLS is unnecessary. It is further obvious, that TLS cannot help in preventing a user to see the data provided through it.

Yes, the table exists. This is a new installation. I haven't done anything, except install it and logging in with the default admin user, yet.

**Comment by marcosboosa** [comment]
hello, I have the same problem.
 I installed a new version 2.1.24.4
![error-ajax](https://cloud.githubusercontent.com/assets/16392414/11942631/11fc6b32-a81f-11e5-9800-86a3a45f24d3.JPG)

 we need a valid certificate? is required ?

**Comment by marcosboosa** [comment]
Hi, it is possible to work around the error?
thanks and regards

**Comment by nilsteampassnet** [comment]
​This defect has been correct in next release.
This message error appears when no user exists in the list.
Create your 1st user and it will not appear.

Please confirm.

**Comment by marcosboosa** [comment]
no, i have create user's, but the error continues!
![error-ajax-mysql-user](https://cloud.githubusercontent.com/assets/16392414/11955137/40d9e08e-a896-11e5-9c3a-bc139fd047dc.JPG)
![error-ajax-user](https://cloud.githubusercontent.com/assets/16392414/11955139/45d84d28-a896-11e5-80a5-e5175dd0416e.JPG)
thanks and regards

**Comment by nilsteampassnet** [comment]
​Can you please provide the answer from the server with the retunred json
data?

You can have it by either use Firebug or the Developer console of your
Browser.

**Comment by marcosboosa** [comment]
yes, error 404.
I think the problem is in the url
![error-ajax-debug](https://cloud.githubusercontent.com/assets/16392414/11961363/25e20954-a8bf-11e5-9d48-2905a36c3a2c.JPG)
![error-ajax-debug-1](https://cloud.githubusercontent.com/assets/16392414/11961364/25e47414-a8bf-11e5-906f-72c718e9788f.JPG)

URL        Protocol              Method               Result   Type      Received             Taken   Initiator               Wait‎‎      Start‎‎      Request‎‎                Response‎‎            Cache read‎‎         Gap‎‎
/sources/datatable/datatable.users.php?draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=false&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=false&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=false&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=false&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=5&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=false&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=6&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=false&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=7&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=false&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B8%5D%5Bdata%5D=8&columns%5B8%5D%5Bname%5D=&columns%5B8%5D%5Bsearchable%5D=true&columns%5B8%5D%5Borderable%5D=false&columns%5B8%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B8%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B9%5D%5Bdata%5D=9&columns%5B9%5D%5Bname%5D=&columns%5B9%5D%5Bsearchable%5D=true&columns%5B9%5D%5Borderable%5D=false&columns%5B9%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B9%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B10%5D%5Bdata%5D=10&columns%5B10%5D%5Bname%5D=&columns%5B10%5D%5Bsearchable%5D=true&columns%5B10%5D%5Borderable%5D=false&columns%5B10%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B10%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B11%5D%5Bdata%5D=11&columns%5B11%5D%5Bname%5D=&columns%5B11%5D%5Bsearchable%5D=true&columns%5B11%5D%5Borderable%5D=false&columns%5B11%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B11%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B12%5D%5Bdata%5D=12&columns%5B12%5D%5Bname%5D=&columns%5B12%5D%5Bsearchable%5D=true&columns%5B12%5D%5Borderable%5D=false&columns%5B12%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B12%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B13%5D%5Bdata%5D=13&columns%5B13%5D%5Bname%5D=&columns%5B13%5D%5Bsearchable%5D=true&columns%5B13%5D%5Borderable%5D=false&columns%5B13%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B13%5D%5Bsearch%5D%5Bregex%5D=false&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&letter=&_=1450724530834    HTTP     GET        404         text/html            1,64 KB 93 ms    XMLHttpRequest                2278      0             93           0             0             8456

**Comment by marcosboosa** [comment]
hi, i instaled the new version 2.1.25, but the error persists.
i created some user, error again.
please help ?
