### ISSUE TITLE
Decryption key not working after generating off-line mode file

### ISSUE THREAD

**Issue by sjaredj** [nilsteampassnet/TeamPass#998]
I was finally able to get off-line mode to generate something after I applied the fix suggested in #513. 

 I am now presented with a "Download file" link.  When I click on it I am taken to an html page labeled "TeamPass - Off Line mode" which asks me to "Enter the decryption key"  I enter my decryption key and hit enter and nothing happens.  I get no entry in the access logs.  The field I entered the password in still is highlighted and the curser is still blinking.  Its like it doesn't recognize that I hit enter.  There is no OK button or anything like that to click on either.  Thinking its a browser issue I tried Safari, Chrome, and Firefox.  All got the same results.  

Any Ideas?

**Comment by rdcobb** [comment]
Same issue. Looking at the provided offline html file, there is not alot in the file - no script, no data, just some html <header> and the start of a <body> and <table>. The file is truncated after the head of the table. Tested on Centos 6.6 (php 5.3.3, teampass 2.1.23) and Centos 7 (with php 5.5.25, teampass 2.1.23). There are no errors displayed in firebug console.

**Comment by sjaredj** [comment]
Anyone have any ideas on this?  I can gather logs, configs, etc, to help troubleshoot this.  This is the last bit of functionality I need before rolling this out to my team.

**Comment by nilsteampassnet** [comment]
I've reperformed tries on my side.
I cannot reproduce this issue.

If you use Firebug, do you get any error that you could communicate?

**Comment by rdcobb** [comment]
This is on a freshly installed CentOS 7 server. SELinux is set to permissive.
Installed and using XAMPP stack (previously using CentOS 7 packages).
Downloaded and set up Teampass 2.1.23
Applied patch for [issue 513](https://github.com/verdel/TeamPass/commit/9617d2e909a2e95db770636492a483e1e9839f49) since I had previously identified this as a problem (off-line mode generation never finishes).
Having done this, offline mode will complete but cuts off the offline html page after the table header was created.
This is the same as the state I was in on 25 June. 
There was no php errors generated in the php error log, no warnings or errors in firebug. No errors in the apache error log.

I have just come across the rest of the fixes verdel submitted (at https://github.com/nilsteampassnet/TeamPass/pull/971). I haven't applied all of them yet, but having applied the: [Fix issue nilsteampassnet#513](https://github.com/verdel/TeamPass/commit/9617d2e909a2e95db770636492a483e1e9839f49), [Fix error with only headers in off-line html file](https://github.com/verdel/TeamPass/commit/b6fe1eb800f083c649a3960bab1bffb92f495bb7) and [Fix empty URL column in off-line html](https://github.com/verdel/TeamPass/commit/2ffe20e8e7eb740609de1a159fecf062f4e0d0ee) the issue is dealt with and offline mode is generating a complete page.
